"""Generated Card 5 step-4 Falco MappingRule specs — review only.

This file is not imported by the runtime.
"""

FALCO_COMMIT = '819918d43a743de78398d0a6ecb75305beeacaaa'

RULE_SPECS = [{'rule': 'CloudTrail Logging Disabled',
  'source_file': 'plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml',
  'technique_id': 'T1685.002',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"eventName")\\s*:\\s*(?-i:")(?-i:StopLogging)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"errorCode")\\s*:\\s*)))[\\s\\S]*\\Z',
                  'technique_name': 'Disable or Modify Cloud Log',
                  'platform': 'aws',
                  'confidence': 'medium',
                  'reason': 'The CloudTrail logging has been disabled, this could be potentially malicious. '
                            '(Falco-sourced).',
                  'source': 'Falco: CloudTrail Logging Disabled',
                  'parent_hint': None}},
 {'rule': 'Console Login Through Assume Role',
  'source_file': 'plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml',
  'technique_id': 'T1078.004',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"eventName")\\s*:\\s*(?-i:")(?-i:ConsoleLogin)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"errorCode")\\s*:\\s*)))(?=[\\s\\S]*(?:(?-i:"userIdentity")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"type")\\s*:\\s*(?-i:")(?-i:AssumedRole)(?-i:")))(?=[\\s\\S]*(?:(?-i:"responseElements")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"ConsoleLogin")\\s*:\\s*(?-i:")(?-i:Success)(?-i:")))[\\s\\S]*\\Z',
                  'technique_name': 'Cloud Accounts',
                  'platform': 'aws',
                  'confidence': 'medium',
                  'reason': 'Detect a console login through Assume Role. (Falco-sourced).',
                  'source': 'Falco: Console Login Through Assume Role',
                  'parent_hint': 'Valid Accounts'}},
 {'rule': 'Console Login Without MFA',
  'source_file': 'plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml',
  'technique_id': 'T1078.004',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"eventName")\\s*:\\s*(?-i:")(?-i:ConsoleLogin)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"errorCode")\\s*:\\s*)))(?!(?=[\\s\\S]*(?:(?-i:"userIdentity")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"type")\\s*:\\s*(?-i:")(?-i:AssumedRole)(?-i:"))))(?=[\\s\\S]*(?:(?-i:"responseElements")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"ConsoleLogin")\\s*:\\s*(?-i:")(?-i:Success)(?-i:")))(?=[\\s\\S]*(?:(?-i:"additionalEventData")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"MFAUsed")\\s*:\\s*(?-i:")(?-i:No)(?-i:")))[\\s\\S]*\\Z',
                  'technique_name': 'Cloud Accounts',
                  'platform': 'aws',
                  'confidence': 'high',
                  'reason': 'Detect a console login without MFA. (Falco-sourced).',
                  'source': 'Falco: Console Login Without MFA',
                  'parent_hint': 'Valid Accounts'}},
 {'rule': 'Console Root Login Without MFA',
  'source_file': 'plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml',
  'technique_id': 'T1078.004',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"eventName")\\s*:\\s*(?-i:")(?-i:ConsoleLogin)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"errorCode")\\s*:\\s*)))(?=[\\s\\S]*(?:(?-i:"additionalEventData")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"MFAUsed")\\s*:\\s*(?-i:")(?-i:No)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"userIdentity")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"type")\\s*:\\s*(?-i:")(?-i:AssumedRole)(?-i:"))))(?=[\\s\\S]*(?:(?-i:"responseElements")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"ConsoleLogin")\\s*:\\s*(?-i:")(?-i:Success)(?-i:")))(?=[\\s\\S]*(?:(?-i:"userIdentity")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"type")\\s*:\\s*(?-i:")(?-i:Root)(?-i:")))[\\s\\S]*\\Z',
                  'technique_name': 'Cloud Accounts',
                  'platform': 'aws',
                  'confidence': 'high',
                  'reason': 'Detect root console login without MFA. (Falco-sourced).',
                  'source': 'Falco: Console Root Login Without MFA',
                  'parent_hint': 'Valid Accounts'}},
 {'rule': 'Create AWS user',
  'source_file': 'plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml',
  'technique_id': 'T1136.003',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"eventName")\\s*:\\s*(?-i:")(?-i:CreateUser)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"errorCode")\\s*:\\s*)))[\\s\\S]*\\Z',
                  'technique_name': 'Cloud Account',
                  'platform': 'aws',
                  'confidence': 'low',
                  'reason': 'Detect creation of a new AWS user. (Falco-sourced).',
                  'source': 'Falco: Create AWS user',
                  'parent_hint': 'Create Account'}},
 {'rule': 'Create Lambda Function',
  'source_file': 'plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml',
  'technique_id': 'T1648',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"eventName")\\s*:\\s*(?-i:")(?-i:CreateFunction20150331)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"errorCode")\\s*:\\s*)))[\\s\\S]*\\Z',
                  'technique_name': 'Serverless Execution',
                  'platform': 'aws',
                  'confidence': 'medium',
                  'reason': 'Detect creation of a Lambda function. (Falco-sourced).',
                  'source': 'Falco: Create Lambda Function',
                  'parent_hint': None}},
 {'rule': 'Deactivate MFA for Root User',
  'source_file': 'plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml',
  'technique_id': 'T1556.006',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"eventName")\\s*:\\s*(?-i:")(?-i:DeactivateMFADevice)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"errorCode")\\s*:\\s*)))(?=[\\s\\S]*(?:(?-i:"userIdentity")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"type")\\s*:\\s*(?-i:")(?-i:Root)(?-i:")))(?=[\\s\\S]*(?:(?-i:"requestParameters")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"userName")\\s*:\\s*(?-i:")(?-i:AWS\\ '
                             'ROOT\\ USER)(?-i:")))[\\s\\S]*\\Z',
                  'technique_name': 'Multi-Factor Authentication',
                  'platform': 'aws',
                  'confidence': 'high',
                  'reason': 'Detect deactivating MFA configuration for root. (Falco-sourced).',
                  'source': 'Falco: Deactivate MFA for Root User',
                  'parent_hint': None}},
 {'rule': 'ECS Service Created',
  'source_file': 'plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml',
  'technique_id': 'T1610',
  'mapping_confidence': 'medium',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"eventSource")\\s*:\\s*(?-i:")(?-i:ecs\\.amazonaws\\.com)(?-i:")))(?=[\\s\\S]*(?:(?-i:"eventName")\\s*:\\s*(?-i:")(?-i:CreateService)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"errorCode")\\s*:\\s*)))[\\s\\S]*\\Z',
                  'technique_name': 'Deploy Container',
                  'platform': 'aws',
                  'confidence': 'medium',
                  'reason': 'Detect a new service is created in ECS. (Falco-sourced).',
                  'source': 'Falco: ECS Service Created',
                  'parent_hint': None}},
 {'rule': 'ECS Task Run or Started',
  'source_file': 'plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml',
  'technique_id': 'T1610',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"eventSource")\\s*:\\s*(?-i:")(?-i:ecs\\.amazonaws\\.com)(?-i:")))(?:(?=[\\s\\S]*(?:(?-i:"eventName")\\s*:\\s*(?-i:")(?-i:RunTask)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"eventName")\\s*:\\s*(?-i:")(?-i:StartTask)(?-i:"))))(?!(?=[\\s\\S]*(?:(?-i:"errorCode")\\s*:\\s*)))[\\s\\S]*\\Z',
                  'technique_name': 'Deploy Container',
                  'platform': 'aws',
                  'confidence': 'medium',
                  'reason': 'Detect a new task is started in ECS. (Falco-sourced).',
                  'source': 'Falco: ECS Task Run or Started',
                  'parent_hint': None}},
 {'rule': 'Run Instances',
  'source_file': 'plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml',
  'technique_id': 'T1578.002',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"eventName")\\s*:\\s*(?-i:")(?-i:RunInstances)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"errorCode")\\s*:\\s*)))[\\s\\S]*\\Z',
                  'technique_name': 'Create Cloud Instance',
                  'platform': 'aws',
                  'confidence': 'medium',
                  'reason': 'Detect launching of a specified number of instances. (Falco-sourced).',
                  'source': 'Falco: Run Instances',
                  'parent_hint': None}},
 {'rule': 'Run Instances in Non-approved Region',
  'source_file': 'plugins/cloudtrail/rules/aws_cloudtrail_rules.yaml',
  'technique_id': 'T1535',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"eventName")\\s*:\\s*(?-i:")(?-i:RunInstances)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"errorCode")\\s*:\\s*)))(?!(?=[\\s\\S]*(?:(?-i:"awsRegion")\\s*:\\s*(?-i:")(?-i:us\\-east\\-0)(?-i:"))))[\\s\\S]*\\Z',
                  'technique_name': 'Unused/Unsupported Cloud Regions',
                  'platform': 'aws',
                  'confidence': 'medium',
                  'reason': 'Detect launching of a specified number of instances in a non-approved region. '
                            '(Falco-sourced).',
                  'source': 'Falco: Run Instances in Non-approved Region',
                  'parent_hint': None}},
 {'rule': 'Anonymous Request Allowed',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1133',
  'mapping_confidence': 'medium',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:system:anonymous)(?-i:")))(?=[\\s\\S]*(?:(?-i:"authorization\\.k8s\\.io/decision")\\s*:\\s*(?-i:")(?-i:allow)(?-i:")))(?!(?:(?=[\\s\\S]*(?:(?-i:"requestURI")\\s*:\\s*(?-i:")(?-i:/healthz)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"requestURI")\\s*:\\s*(?-i:")(?-i:/healthz\\?)[^"\\\\]*(?-i:")))))(?!(?:(?=[\\s\\S]*(?:(?-i:"requestURI")\\s*:\\s*(?-i:")(?-i:/livez)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"requestURI")\\s*:\\s*(?-i:")(?-i:/livez\\?)[^"\\\\]*(?-i:")))))(?!(?:(?=[\\s\\S]*(?:(?-i:"requestURI")\\s*:\\s*(?-i:")(?-i:/readyz)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"requestURI")\\s*:\\s*(?-i:")(?-i:/readyz\\?)[^"\\\\]*(?-i:")))))[\\s\\S]*\\Z',
                  'technique_name': 'External Remote Services',
                  'platform': 'kubernetes',
                  'confidence': 'medium',
                  'reason': 'Detect any request made by the anonymous user that was allowed (Falco-sourced).',
                  'source': 'Falco: Anonymous Request Allowed',
                  'parent_hint': None}},
 {'rule': 'Attach to cluster-admin Role',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1098.006',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:clusterrolebindings)(?-i:")))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))(?=[\\s\\S]*(?:(?-i:"requestObject")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"roleRef")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:cluster\\-admin)(?-i:")))[\\s\\S]*\\Z',
                  'technique_name': 'Additional Container Cluster Roles',
                  'platform': 'kubernetes',
                  'confidence': 'medium',
                  'reason': 'Detect any attempt to create a ClusterRoleBinding to the cluster-admin user '
                            '(Falco-sourced).',
                  'source': 'Falco: Attach to cluster-admin Role',
                  'parent_hint': None}},
 {'rule': 'Attach/Exec Pod',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1609',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseStarted)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:pods)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"subresource")\\s*:\\s*))(?:(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:get)(?-i:"))))(?:(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"subresource")\\s*:\\s*(?-i:")(?-i:exec)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"subresource")\\s*:\\s*(?-i:")(?-i:attach)(?-i:"))))(?!(?=[\\s\\S]*(?:(?!))))[\\s\\S]*\\Z',
                  'technique_name': 'Container Administration Command',
                  'platform': 'kubernetes',
                  'confidence': 'medium',
                  'reason': 'Detect any attempt to attach/exec to a pod (Falco-sourced).',
                  'source': 'Falco: Attach/Exec Pod',
                  'parent_hint': None}},
 {'rule': 'ClusterRole With Pod Exec Created',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1098.006',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?:(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:roles)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:clusterroles)(?-i:"))))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))(?=[\\s\\S]*(?:(?-i:"resources")\\s*:\\s*\\[[^\\]]*(?-i:")(?-i:pods/exec)(?-i:")[^\\]]*\\]))[\\s\\S]*\\Z',
                  'technique_name': 'Additional Container Cluster Roles',
                  'platform': 'kubernetes',
                  'confidence': 'medium',
                  'reason': 'Detect any attempt to create a Role/ClusterRole that can exec to pods (Falco-sourced).',
                  'source': 'Falco: ClusterRole With Pod Exec Created',
                  'parent_hint': None}},
 {'rule': 'ClusterRole With Wildcard Created',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1098.006',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?:(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:roles)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:clusterroles)(?-i:"))))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))(?:(?=[\\s\\S]*(?:(?-i:"resources")\\s*:\\s*\\[[^\\]]*(?-i:")(?-i:\\*)(?-i:")[^\\]]*\\]))|(?=[\\s\\S]*(?:(?-i:"verbs")\\s*:\\s*\\[[^\\]]*(?-i:")(?-i:\\*)(?-i:")[^\\]]*\\])))[\\s\\S]*\\Z',
                  'technique_name': 'Additional Container Cluster Roles',
                  'platform': 'kubernetes',
                  'confidence': 'medium',
                  'reason': 'Detect any attempt to create a Role/ClusterRole with wildcard resources or verbs '
                            '(Falco-sourced).',
                  'source': 'Falco: ClusterRole With Wildcard Created',
                  'parent_hint': None}},
 {'rule': 'ClusterRole With Write Privileges Created',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1098.006',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?:(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:roles)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:clusterroles)(?-i:"))))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))(?:(?=[\\s\\S]*(?:(?-i:"verbs")\\s*:\\s*\\[[^\\]]*(?-i:")(?-i:create)(?-i:")[^\\]]*\\]))|(?=[\\s\\S]*(?:(?-i:"verbs")\\s*:\\s*\\[[^\\]]*(?-i:")(?-i:update)(?-i:")[^\\]]*\\]))|(?=[\\s\\S]*(?:(?-i:"verbs")\\s*:\\s*\\[[^\\]]*(?-i:")(?-i:patch)(?-i:")[^\\]]*\\]))|(?=[\\s\\S]*(?:(?-i:"verbs")\\s*:\\s*\\[[^\\]]*(?-i:")(?-i:delete)(?-i:")[^\\]]*\\]))|(?=[\\s\\S]*(?:(?-i:"verbs")\\s*:\\s*\\[[^\\]]*(?-i:")(?-i:deletecollection)(?-i:")[^\\]]*\\])))[\\s\\S]*\\Z',
                  'technique_name': 'Additional Container Cluster Roles',
                  'platform': 'kubernetes',
                  'confidence': 'medium',
                  'reason': 'Detect any attempt to create a Role/ClusterRole that can perform write-related actions '
                            '(Falco-sourced).',
                  'source': 'Falco: ClusterRole With Write Privileges Created',
                  'parent_hint': None}},
 {'rule': 'Create HostIPC Pod',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1610',
  'mapping_confidence': 'medium',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:pods)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"subresource")\\s*:\\s*)))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))(?=[\\s\\S]*(?:(?-i:"requestObject")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"spec")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"hostIPC")\\s*:\\s*(?-i:true)))(?!(?=[\\s\\S]*(?:(?!))))[\\s\\S]*\\Z',
                  'technique_name': 'Deploy Container',
                  'platform': 'kubernetes',
                  'confidence': 'medium',
                  'reason': 'Detect an attempt to start a pod using the host ipc namespace. (Falco-sourced).',
                  'source': 'Falco: Create HostIPC Pod',
                  'parent_hint': None}},
 {'rule': 'Create HostNetwork Pod',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1610',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:pods)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"subresource")\\s*:\\s*)))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))(?=[\\s\\S]*(?:(?-i:"requestObject")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"spec")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"hostNetwork")\\s*:\\s*(?-i:true)))(?!(?=[\\s\\S]*(?:(?-i:"image")\\s*:\\s*(?-i:")[^"\\\\]+(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"image")\\s*:\\s*(?-i:")(?!(?:(?-i:gcr\\.io/google\\-containers/prometheus\\-to\\-sd)(?=(?-i::|@|\\"))|(?-i:gcr\\.io/projectcalico\\-org/typha)(?=(?-i::|@|\\"))|(?-i:gcr\\.io/projectcalico\\-org/node)(?=(?-i::|@|\\"))|(?-i:gke\\.gcr\\.io/gke\\-metadata\\-server)(?=(?-i::|@|\\"))|(?-i:gke\\.gcr\\.io/kube\\-proxy)(?=(?-i::|@|\\"))|(?-i:gke\\.gcr\\.io/netd\\-amd64)(?=(?-i::|@|\\"))|(?-i:registry\\.k8s\\.io/ip\\-masq\\-agent\\-amd64)(?=(?-i::|@|\\"))|(?-i:registry\\.k8s\\.io/prometheus\\-to\\-sd)(?=(?-i::|@|\\"))))[^"\\\\]+(?-i:")))))[\\s\\S]*\\Z',
                  'technique_name': 'Deploy Container',
                  'platform': 'kubernetes',
                  'confidence': 'medium',
                  'reason': 'Detect an attempt to start a pod using the host network. (Falco-sourced).',
                  'source': 'Falco: Create HostNetwork Pod',
                  'parent_hint': None}},
 {'rule': 'Create HostPid Pod',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1610',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:pods)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"subresource")\\s*:\\s*)))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))(?=[\\s\\S]*(?:(?-i:"requestObject")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"spec")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"hostPID")\\s*:\\s*(?-i:true)))(?!(?=[\\s\\S]*(?:(?!))))[\\s\\S]*\\Z',
                  'technique_name': 'Deploy Container',
                  'platform': 'kubernetes',
                  'confidence': 'medium',
                  'reason': 'Detect an attempt to start a pod using the host pid namespace. (Falco-sourced).',
                  'source': 'Falco: Create HostPid Pod',
                  'parent_hint': None}},
 {'rule': 'Create Privileged Pod',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1610',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:pods)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"subresource")\\s*:\\s*)))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))(?:(?=[\\s\\S]*(?:(?-i:"privileged")\\s*:\\s*(?-i:true)))|(?=[\\s\\S]*(?:(?-i:"privileged")\\s*:\\s*(?-i:true)))|(?=[\\s\\S]*(?:(?-i:"privileged")\\s*:\\s*(?-i:true))))(?!(?=[\\s\\S]*(?:(?-i:"image")\\s*:\\s*(?-i:")[^"\\\\]+(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"image")\\s*:\\s*(?-i:")(?!(?:(?-i:falcosecurity/falco)(?=(?-i::|@|\\"))|(?-i:docker\\.io/falcosecurity/falco)(?=(?-i::|@|\\"))|(?-i:public\\.ecr\\.aws/falcosecurity/falco)(?=(?-i::|@|\\"))|(?-i:docker\\.io/calico/node)(?=(?-i::|@|\\"))|(?-i:calico/node)(?=(?-i::|@|\\"))|(?-i:docker\\.io/cloudnativelabs/kube\\-router)(?=(?-i::|@|\\"))|(?-i:docker\\.io/docker/ucp\\-agent)(?=(?-i::|@|\\"))|(?-i:docker\\.io/mesosphere/mesos\\-slave)(?=(?-i::|@|\\"))|(?-i:docker\\.io/rook/toolbox)(?=(?-i::|@|\\"))|(?-i:docker\\.io/sysdig/sysdig)(?=(?-i::|@|\\"))|(?-i:gcr\\.io/google_containers/kube\\-proxy)(?=(?-i::|@|\\"))|(?-i:gcr\\.io/google\\-containers/startup\\-script)(?=(?-i::|@|\\"))|(?-i:gcr\\.io/projectcalico\\-org/node)(?=(?-i::|@|\\"))|(?-i:gke\\.gcr\\.io/kube\\-proxy)(?=(?-i::|@|\\"))|(?-i:gke\\.gcr\\.io/gke\\-metadata\\-server)(?=(?-i::|@|\\"))|(?-i:gke\\.gcr\\.io/netd\\-amd64)(?=(?-i::|@|\\"))|(?-i:gke\\.gcr\\.io/watcher\\-daemonset)(?=(?-i::|@|\\"))|(?-i:gcr\\.io/google\\-containers/prometheus\\-to\\-sd)(?=(?-i::|@|\\"))|(?-i:registry\\.k8s\\.io/ip\\-masq\\-agent\\-amd64)(?=(?-i::|@|\\"))|(?-i:registry\\.k8s\\.io/kube\\-proxy)(?=(?-i::|@|\\"))|(?-i:registry\\.k8s\\.io/prometheus\\-to\\-sd)(?=(?-i::|@|\\"))|(?-i:quay\\.io/calico/node)(?=(?-i::|@|\\"))|(?-i:sysdig/sysdig)(?=(?-i::|@|\\"))|(?-i:registry\\.k8s\\.io/dns/k8s\\-dns\\-node\\-cache)(?=(?-i::|@|\\"))|(?-i:mcr\\.microsoft\\.com/oss/kubernetes/kube\\-proxy)(?=(?-i::|@|\\"))))[^"\\\\]+(?-i:")))))[\\s\\S]*\\Z',
                  'technique_name': 'Deploy Container',
                  'platform': 'kubernetes',
                  'confidence': 'medium',
                  'reason': 'Detect an attempt to start a pod with a privileged container (Falco-sourced).',
                  'source': 'Falco: Create Privileged Pod',
                  'parent_hint': None}},
 {'rule': 'Create Sensitive Mount Pod',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1610',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:pods)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"subresource")\\s*:\\s*)))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))(?:(?=[\\s\\S]*(?:(?-i:"requestObject")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"spec")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"volumes")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"hostPath")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"path")\\s*:\\s*(?-i:")(?-i:/proc)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"requestObject")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"spec")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"volumes")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"hostPath")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"path")\\s*:\\s*(?-i:")(?-i:/var/run/docker\\.sock)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"requestObject")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"spec")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"volumes")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"hostPath")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"path")\\s*:\\s*(?-i:")(?-i:/)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"requestObject")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"spec")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"volumes")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"hostPath")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"path")\\s*:\\s*(?-i:")(?-i:/etc)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"requestObject")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"spec")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"volumes")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"hostPath")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"path")\\s*:\\s*(?-i:")(?-i:/root)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"requestObject")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"spec")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"volumes")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"hostPath")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"path")\\s*:\\s*(?-i:")(?-i:/var/run/crio/crio\\.sock)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"requestObject")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"spec")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"volumes")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"hostPath")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"path")\\s*:\\s*(?-i:")(?-i:/run/containerd/containerd\\.sock)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"requestObject")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"spec")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"volumes")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"hostPath")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"path")\\s*:\\s*(?-i:")(?-i:/home/admin)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"requestObject")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"spec")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"volumes")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"hostPath")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"path")\\s*:\\s*(?-i:")(?-i:/var/lib/kubelet)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"requestObject")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"spec")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"volumes")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"hostPath")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"path")\\s*:\\s*(?-i:")(?-i:/var/lib/kubelet/pki)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"requestObject")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"spec")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"volumes")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"hostPath")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"path")\\s*:\\s*(?-i:")(?-i:/etc/kubernetes)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"requestObject")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"spec")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"volumes")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"hostPath")\\s*:\\s*(?:\\{|\\[)[\\s\\S]{0,6000}?(?-i:"path")\\s*:\\s*(?-i:")(?-i:/etc/kubernetes/manifests)(?-i:"))))(?!(?=[\\s\\S]*(?:(?-i:"image")\\s*:\\s*(?-i:")[^"\\\\]+(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"image")\\s*:\\s*(?-i:")(?!(?:(?-i:falcosecurity/falco)(?=(?-i::|@|\\"))|(?-i:docker\\.io/falcosecurity/falco)(?=(?-i::|@|\\"))|(?-i:public\\.ecr\\.aws/falcosecurity/falco)(?=(?-i::|@|\\"))|(?-i:docker\\.io/sysdig/sysdig)(?=(?-i::|@|\\"))|(?-i:sysdig/sysdig)(?=(?-i::|@|\\"))|(?-i:gcr\\.io/google_containers/hyperkube)(?=(?-i::|@|\\"))|(?-i:gcr\\.io/google_containers/kube\\-proxy)(?=(?-i::|@|\\"))|(?-i:docker\\.io/calico/node)(?=(?-i::|@|\\"))|(?-i:docker\\.io/rook/toolbox)(?=(?-i::|@|\\"))|(?-i:docker\\.io/cloudnativelabs/kube\\-router)(?=(?-i::|@|\\"))|(?-i:docker\\.io/consul)(?=(?-i::|@|\\"))|(?-i:docker\\.io/datadog/docker\\-dd\\-agent)(?=(?-i::|@|\\"))|(?-i:docker\\.io/datadog/agent)(?=(?-i::|@|\\"))|(?-i:docker\\.io/docker/ucp\\-agent)(?=(?-i::|@|\\"))|(?-i:docker\\.io/gliderlabs/logspout)(?=(?-i::|@|\\"))|(?-i:docker\\.io/netdata/netdata)(?=(?-i::|@|\\"))|(?-i:docker\\.io/google/cadvisor)(?=(?-i::|@|\\"))|(?-i:docker\\.io/prom/node\\-exporter)(?=(?-i::|@|\\"))|(?-i:amazon/amazon\\-ecs\\-agent)(?=(?-i::|@|\\"))|(?-i:prom/node\\-exporter)(?=(?-i::|@|\\"))|(?-i:amazon/cloudwatch\\-agent)(?=(?-i::|@|\\"))))[^"\\\\]+(?-i:")))))[\\s\\S]*\\Z',
                  'technique_name': 'Deploy Container',
                  'platform': 'kubernetes',
                  'confidence': 'medium',
                  'reason': 'Detect an attempt to start a pod with a volume from a sensitive host directory (i.e. '
                            '/proc). Exceptions are made for known trusted images. (Falco-sourced).',
                  'source': 'Falco: Create Sensitive Mount Pod',
                  'parent_hint': None}},
 {'rule': 'Disallowed K8s User',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1078',
  'mapping_confidence': 'medium',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:system:)[^"\\\\]*(?-i:"))))(?!(?:(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:minikube)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:minikube\\-user)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:kubelet)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:kops)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:admin)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:kube)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:kube\\-proxy)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:kube\\-apiserver\\-healthcheck)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:kubernetes\\-admin)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:vpa\\-recommender)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:vpa\\-updater)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:cluster\\-autoscaler)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:system:addon\\-manager)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:cloud\\-controller\\-manager)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:system:kube\\-controller\\-manager)(?-i:")))))(?!(?:(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:eks:node\\-manager)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:eks:certificate\\-controller)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:eks:fargate\\-scheduler)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:eks:k8s\\-metrics)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:eks:authenticator)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:eks:cluster\\-event\\-watcher)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:eks:nodewatcher)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:eks:pod\\-identity\\-mutating\\-webhook)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:eks:cloud\\-controller\\-manager)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:eks:vpc\\-resource\\-controller)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:eks:addon\\-manager)(?-i:")))))[\\s\\S]*\\Z',
                  'technique_name': 'Valid Accounts',
                  'platform': 'kubernetes',
                  'confidence': 'medium',
                  'reason': 'Detect any k8s operation by users outside of an allowed set of users. (Falco-sourced).',
                  'source': 'Falco: Disallowed K8s User',
                  'parent_hint': None}},
 {'rule': 'EphemeralContainers Created',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1610',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:pods)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"subresource")\\s*:\\s*))(?:(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:update)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:patch)(?-i:"))))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"subresource")\\s*:\\s*(?-i:")(?-i:ephemeralcontainers)(?-i:")))(?!(?=[\\s\\S]*(?:(?!))))[\\s\\S]*\\Z',
                  'technique_name': 'Deploy Container',
                  'platform': 'kubernetes',
                  'confidence': 'medium',
                  'reason': 'Detect any ephemeral container created (Falco-sourced).',
                  'source': 'Falco: EphemeralContainers Created',
                  'parent_hint': None}},
 {'rule': 'K8s ClusterRole Created',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1098.006',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:[\\s\\S]*))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:clusterroles)(?-i:")))(?=[\\s\\S]*(?:(?-i:"responseStatus")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"code")\\s*:\\s*(?:(?-i:2)[0-9]*|(?-i:")(?-i:2)[0-9]*(?-i:"))))[\\s\\S]*\\Z',
                  'technique_name': 'Additional Container Cluster Roles',
                  'platform': 'kubernetes',
                  'confidence': 'low',
                  'reason': 'Detect any attempt to create a cluster role (Falco-sourced).',
                  'source': 'Falco: K8s ClusterRole Created',
                  'parent_hint': None}},
 {'rule': 'K8s ClusterRoleBinding Created',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1098.006',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:[\\s\\S]*))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:clusterrolebindings)(?-i:")))(?=[\\s\\S]*(?:(?-i:"responseStatus")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"code")\\s*:\\s*(?:(?-i:2)[0-9]*|(?-i:")(?-i:2)[0-9]*(?-i:"))))[\\s\\S]*\\Z',
                  'technique_name': 'Additional Container Cluster Roles',
                  'platform': 'kubernetes',
                  'confidence': 'low',
                  'reason': 'Detect any attempt to create a clusterrolebinding (Falco-sourced).',
                  'source': 'Falco: K8s ClusterRoleBinding Created',
                  'parent_hint': None}},
 {'rule': 'K8s ConfigMap Deleted',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1485',
  'mapping_confidence': 'medium',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:[\\s\\S]*))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:delete)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:configmaps)(?-i:")))(?=[\\s\\S]*(?:(?-i:"responseStatus")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"code")\\s*:\\s*(?:(?-i:2)[0-9]*|(?-i:")(?-i:2)[0-9]*(?-i:"))))[\\s\\S]*\\Z',
                  'technique_name': 'Data Destruction',
                  'platform': 'kubernetes',
                  'confidence': 'low',
                  'reason': 'Detect any attempt to delete a configmap (Falco-sourced).',
                  'source': 'Falco: K8s ConfigMap Deleted',
                  'parent_hint': None}},
 {'rule': 'K8s Deployment Created',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1610',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:[\\s\\S]*))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:deployments)(?-i:")))(?=[\\s\\S]*(?:(?-i:"responseStatus")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"code")\\s*:\\s*(?:(?-i:2)[0-9]*|(?-i:")(?-i:2)[0-9]*(?-i:"))))[\\s\\S]*\\Z',
                  'technique_name': 'Deploy Container',
                  'platform': 'kubernetes',
                  'confidence': 'low',
                  'reason': 'Detect any attempt to create a deployment (Falco-sourced).',
                  'source': 'Falco: K8s Deployment Created',
                  'parent_hint': None}},
 {'rule': 'K8s Deployment Deleted',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1485',
  'mapping_confidence': 'medium',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:[\\s\\S]*))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:delete)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:deployments)(?-i:")))(?=[\\s\\S]*(?:(?-i:"responseStatus")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"code")\\s*:\\s*(?:(?-i:2)[0-9]*|(?-i:")(?-i:2)[0-9]*(?-i:"))))[\\s\\S]*\\Z',
                  'technique_name': 'Data Destruction',
                  'platform': 'kubernetes',
                  'confidence': 'low',
                  'reason': 'Detect any attempt to delete a deployment (Falco-sourced).',
                  'source': 'Falco: K8s Deployment Deleted',
                  'parent_hint': None}},
 {'rule': 'K8s Namespace Deleted',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1485',
  'mapping_confidence': 'medium',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:[\\s\\S]*))(?!(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:system:)[^"\\\\]*(?-i:"))))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:delete)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:namespaces)(?-i:")))(?=[\\s\\S]*(?:(?-i:"responseStatus")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"code")\\s*:\\s*(?:(?-i:2)[0-9]*|(?-i:")(?-i:2)[0-9]*(?-i:"))))[\\s\\S]*\\Z',
                  'technique_name': 'Data Destruction',
                  'platform': 'kubernetes',
                  'confidence': 'low',
                  'reason': 'Detect any attempt to delete a namespace (Falco-sourced).',
                  'source': 'Falco: K8s Namespace Deleted',
                  'parent_hint': None}},
 {'rule': 'K8s Role Created',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1098.006',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:[\\s\\S]*))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:roles)(?-i:")))(?=[\\s\\S]*(?:(?-i:"responseStatus")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"code")\\s*:\\s*(?:(?-i:2)[0-9]*|(?-i:")(?-i:2)[0-9]*(?-i:"))))[\\s\\S]*\\Z',
                  'technique_name': 'Additional Container Cluster Roles',
                  'platform': 'kubernetes',
                  'confidence': 'low',
                  'reason': 'Detect any attempt to create a role (Falco-sourced).',
                  'source': 'Falco: K8s Role Created',
                  'parent_hint': None}},
 {'rule': 'K8s RoleBinding Created',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1098.006',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:[\\s\\S]*))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:rolebindings)(?-i:")))(?=[\\s\\S]*(?:(?-i:"responseStatus")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"code")\\s*:\\s*(?:(?-i:2)[0-9]*|(?-i:")(?-i:2)[0-9]*(?-i:"))))[\\s\\S]*\\Z',
                  'technique_name': 'Additional Container Cluster Roles',
                  'platform': 'kubernetes',
                  'confidence': 'low',
                  'reason': 'Detect any attempt to create a rolebinding (Falco-sourced).',
                  'source': 'Falco: K8s RoleBinding Created',
                  'parent_hint': None}},
 {'rule': 'K8s Secret Deleted',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1485',
  'mapping_confidence': 'medium',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:[\\s\\S]*))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:delete)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:secrets)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"namespace")\\s*:\\s*(?-i:")(?-i:kube\\-system)(?-i:"))))(?!(?=[\\s\\S]*(?:(?-i:"user")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"username")\\s*:\\s*(?-i:")(?-i:system:)[^"\\\\]*(?-i:"))))(?=[\\s\\S]*(?:(?-i:"responseStatus")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"code")\\s*:\\s*(?:(?-i:2)[0-9]*|(?-i:")(?-i:2)[0-9]*(?-i:"))))[\\s\\S]*\\Z',
                  'technique_name': 'Data Destruction',
                  'platform': 'kubernetes',
                  'confidence': 'low',
                  'reason': 'Detect any attempt to delete a secret. Service account tokens are excluded. '
                            '(Falco-sourced).',
                  'source': 'Falco: K8s Secret Deleted',
                  'parent_hint': None}},
 {'rule': 'K8s Secret Get Successfully',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1552.007',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:secrets)(?-i:")))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:get)(?-i:")))(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:[\\s\\S]*))(?=[\\s\\S]*(?:(?-i:"responseStatus")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"code")\\s*:\\s*(?:(?-i:2)[0-9]*|(?-i:")(?-i:2)[0-9]*(?-i:"))))[\\s\\S]*\\Z',
                  'technique_name': 'Container API',
                  'platform': 'kubernetes',
                  'confidence': 'high',
                  'reason': 'Detect any attempt to get a secret. Service account tokens are excluded. (Falco-sourced).',
                  'source': 'Falco: K8s Secret Get Successfully',
                  'parent_hint': None}},
 {'rule': 'K8s Secret Get Unsuccessfully Tried',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1552.007',
  'mapping_confidence': 'high',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:secrets)(?-i:")))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:get)(?-i:")))(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:[\\s\\S]*))(?!(?=[\\s\\S]*(?:(?-i:"responseStatus")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"code")\\s*:\\s*(?:(?-i:2)[0-9]*|(?-i:")(?-i:2)[0-9]*(?-i:")))))[\\s\\S]*\\Z',
                  'technique_name': 'Container API',
                  'platform': 'kubernetes',
                  'confidence': 'medium',
                  'reason': 'Detect an unsuccessful attempt to get the secret. Service account tokens are excluded. '
                            '(Falco-sourced).',
                  'source': 'Falco: K8s Secret Get Unsuccessfully Tried',
                  'parent_hint': None}},
 {'rule': 'K8s Serviceaccount Created',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1136',
  'mapping_confidence': 'medium',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:[\\s\\S]*))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:serviceaccounts)(?-i:")))(?=[\\s\\S]*(?:(?-i:"responseStatus")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"code")\\s*:\\s*(?:(?-i:2)[0-9]*|(?-i:")(?-i:2)[0-9]*(?-i:"))))[\\s\\S]*\\Z',
                  'technique_name': 'Create Account',
                  'platform': 'kubernetes',
                  'confidence': 'low',
                  'reason': 'Detect any attempt to create a service account (Falco-sourced).',
                  'source': 'Falco: K8s Serviceaccount Created',
                  'parent_hint': None}},
 {'rule': 'Pod Created in Kube Namespace',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1036.005',
  'mapping_confidence': 'medium',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:pods)(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"subresource")\\s*:\\s*)))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))(?:(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"namespace")\\s*:\\s*(?-i:")(?-i:kube\\-system)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"namespace")\\s*:\\s*(?-i:")(?-i:kube\\-public)(?-i:"))))(?!(?:(?=[\\s\\S]*(?:(?!)))|(?=[\\s\\S]*(?:(?-i:"image")\\s*:\\s*(?-i:")[^"\\\\]+(?-i:")))(?!(?=[\\s\\S]*(?:(?-i:"image")\\s*:\\s*(?-i:")(?!(?:(?-i:gcr\\.io/google\\-containers/prometheus\\-to\\-sd)(?=(?-i::|@|\\"))|(?-i:gcr\\.io/projectcalico\\-org/node)(?=(?-i::|@|\\"))|(?-i:gke\\.gcr\\.io/addon\\-resizer)(?=(?-i::|@|\\"))|(?-i:gke\\.gcr\\.io/heapster)(?=(?-i::|@|\\"))|(?-i:gke\\.gcr\\.io/gke\\-metadata\\-server)(?=(?-i::|@|\\"))|(?-i:registry\\.k8s\\.io/ip\\-masq\\-agent\\-amd64)(?=(?-i::|@|\\"))|(?-i:registry\\.k8s\\.io/kube\\-apiserver)(?=(?-i::|@|\\"))|(?-i:gke\\.gcr\\.io/kube\\-proxy)(?=(?-i::|@|\\"))|(?-i:gke\\.gcr\\.io/netd\\-amd64)(?=(?-i::|@|\\"))|(?-i:gke\\.gcr\\.io/watcher\\-daemonset)(?=(?-i::|@|\\"))|(?-i:registry\\.k8s\\.io/addon\\-resizer)(?=(?-i::|@|\\"))|(?-i:registry\\.k8s\\.io/prometheus\\-to\\-sd)(?=(?-i::|@|\\"))|(?-i:registry\\.k8s\\.io/k8s\\-dns\\-dnsmasq\\-nanny\\-amd64)(?=(?-i::|@|\\"))|(?-i:registry\\.k8s\\.io/k8s\\-dns\\-kube\\-dns\\-amd64)(?=(?-i::|@|\\"))|(?-i:registry\\.k8s\\.io/k8s\\-dns\\-sidecar\\-amd64)(?=(?-i::|@|\\"))|(?-i:registry\\.k8s\\.io/metrics\\-server\\-amd64)(?=(?-i::|@|\\"))|(?-i:kope/kube\\-apiserver\\-healthcheck)(?=(?-i::|@|\\"))))[^"\\\\]+(?-i:"))))))[\\s\\S]*\\Z',
                  'technique_name': 'Match Legitimate Resource Name or Location',
                  'platform': 'kubernetes',
                  'confidence': 'medium',
                  'reason': 'Detect any attempt to create a pod in the kube-system or kube-public namespaces '
                            '(Falco-sourced).',
                  'source': 'Falco: Pod Created in Kube Namespace',
                  'parent_hint': None}},
 {'rule': 'Service Account Created in Kube Namespace',
  'source_file': 'plugins/k8saudit/rules/k8s_audit_rules.yaml',
  'technique_id': 'T1136',
  'mapping_confidence': 'medium',
  'rule_kwargs': {'pattern': '\\A(?=[\\s\\S]*(?:(?-i:"stage")\\s*:\\s*(?-i:")(?-i:ResponseComplete)(?-i:")))(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"resource")\\s*:\\s*(?-i:")(?-i:serviceaccounts)(?-i:")))(?=[\\s\\S]*(?:(?-i:"verb")\\s*:\\s*(?-i:")(?-i:create)(?-i:")))(?:(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"namespace")\\s*:\\s*(?-i:")(?-i:kube\\-system)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"namespace")\\s*:\\s*(?-i:")(?-i:kube\\-public)(?-i:"))))(?=[\\s\\S]*(?:(?-i:"responseStatus")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"code")\\s*:\\s*(?:(?-i:2)[0-9]*|(?-i:")(?-i:2)[0-9]*(?-i:"))))(?!(?:(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:coredns)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:coredns\\-autoscaler)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:cronjob\\-controller)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:daemon\\-set\\-controller)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:deployment\\-controller)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:disruption\\-controller)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:endpoint\\-controller)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:endpointslice\\-controller)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:endpointslicemirroring\\-controller)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:generic\\-garbage\\-collector)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:horizontal\\-pod\\-autoscaler)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:job\\-controller)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:namespace\\-controller)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:node\\-controller)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:persistent\\-volume\\-binder)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:pod\\-garbage\\-collector)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:pv\\-protection\\-controller)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:pvc\\-protection\\-controller)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:replicaset\\-controller)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:resourcequota\\-controller)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:root\\-ca\\-cert\\-publisher)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:service\\-account\\-controller)(?-i:")))|(?=[\\s\\S]*(?:(?-i:"objectRef")\\s*:\\s*\\{[^{}]{0,2000}?(?-i:"name")\\s*:\\s*(?-i:")(?-i:statefulset\\-controller)(?-i:")))))[\\s\\S]*\\Z',
                  'technique_name': 'Create Account',
                  'platform': 'kubernetes',
                  'confidence': 'medium',
                  'reason': 'Detect any attempt to create a serviceaccount in the kube-system or kube-public '
                            'namespaces (Falco-sourced).',
                  'source': 'Falco: Service Account Created in Kube Namespace',
                  'parent_hint': None}}]
