"""Deterministic indicator -> ATT&CK technique-name mapping rules.

Every rule maps to a technique NAME, never a hardcoded technique_id - the
actual ID is resolved live against the Neo4j graph (see analyzer.py), so a
future MITRE renumbering (as happened in ATT&CK v19 - see the research notes
in this card's history) can never make a rule point at a stale ID.

Sourced from Sigma, Atomic Red Team, MITRE CAR/DeTT&CT, LOLBAS (Windows),
GTFOBins (Linux). Each rule's `source` field cites exactly where it came
from so a reviewer can re-verify it later.
"""

import re
from dataclasses import dataclass
from typing import Any, Mapping, Sequence

from log_analysis.runtime_rules import load_runtime_rule_records
from log_analysis.structured import StructuredCondition


@dataclass(frozen=True)
class MappingRule:
    pattern: re.Pattern
    technique_name: str
    platform: str
    confidence: str
    reason: str
    source: str
    structured_condition: StructuredCondition | None = None
    # A semantics-preserving fast path for offline-compiled raw rules. At
    # least one alternative term must occur before regex evaluation.
    prefilter_terms: tuple[str, ...] = ()
    # Only set for the handful of sub-technique names that MITRE reuses
    # under more than one parent (e.g. "Cloud Account" exists under both
    # Account Discovery and Create Account) - lets fetch_nodes_by_names
    # disambiguate via the graph's SUBTECHNIQUE_OF relationship instead of
    # guessing from name alone.
    parent_hint: str | None = None


def _rule(
    pattern: str,
    technique_name: str,
    platform: str,
    confidence: str,
    reason: str,
    source: str,
    parent_hint: str | None = None,
    structured_condition: Mapping[str, Any] | None = None,
    prefilter_terms: Sequence[str] | None = None,
) -> MappingRule:
    return MappingRule(
        pattern=re.compile(pattern, re.IGNORECASE),
        technique_name=technique_name,
        platform=platform,
        confidence=confidence,
        reason=reason,
        source=source,
        structured_condition=(
            StructuredCondition.from_dict(structured_condition)
            if structured_condition is not None
            else None
        ),
        prefilter_terms=tuple(term.casefold() for term in (prefilter_terms or ())),
        parent_hint=parent_hint,
    )


WINDOWS_RULES: list[MappingRule] = [
    _rule(r"\bwhoami(?:\.exe)?\b(?:\s+/all)?", "System Owner/User Discovery", "windows", "high",
          "whoami execution identifies the current account and privilege context.",
          "MITRE ATT&CK T1033 / Sigma process creation analytics"),
    _rule(r"\bnet(?:\.exe)?\s+group\b.{0,80}(?:domain\s+admins|/domain)", "Permission Groups Discovery", "windows", "high",
          "Domain group enumeration maps privileged group membership.",
          "Atomic Red Team T1069.002"),
    _rule(r"\bnet(?:\.exe)?\s+view\b(?:\s+/domain)?", "Remote System Discovery", "windows", "high",
          "net view enumerates reachable systems or domains for lateral movement planning.",
          "Atomic Red Team T1018"),
    _rule(r"reg(?:\.exe)?\s+save\s+hklm\\sam\b|\bsam\.save\b", "Security Account Manager", "windows", "high",
          "Saving the SAM registry hive is the classic offline-crackable credential-dumping step.",
          "Atomic Red Team T1003.002 / MITRE CAR"),
    _rule(r"reg(?:\.exe)?\s+save\s+hklm\\(?:security|system)\b", "LSA Secrets", "windows", "high",
          "Dumping SECURITY+SYSTEM hives together enables offline LSA secrets decryption.",
          "Atomic Red Team T1003.004"),
    _rule(r"comsvcs\.dll\s*,\s*minidump|rundll32.{0,40}comsvcs\.dll", "LSASS Memory", "windows", "high",
          "comsvcs.dll's MiniDump export dumps LSASS without needing procdump/Mimikatz on disk.",
          "LOLBAS: comsvcs.dll"),
    _rule(r"procdump.{0,20}-ma\s+ls|procdump.{0,20}lsass", "LSASS Memory", "windows", "high",
          "Sysinternals ProcDump full-memory dump of lsass.exe.",
          "Sigma: proc_creation_win_procdump_lsass"),
    _rule(r"rundll32(?:\.exe)?\b.{0,120}(?:\.dll|javascript:|url\.dll|shell32\.dll|comsvcs\.dll)", "Rundll32", "windows", "high",
          "rundll32 executing DLL exports or script/proxy patterns is a common signed-binary proxy execution technique.",
          "LOLBAS: Rundll32.exe / Atomic Red Team T1218.011"),
    _rule(r"sekurlsa::", "LSASS Memory", "windows", "high",
          "sekurlsa is the Mimikatz module name specific to LSASS memory extraction.",
          "Sigma: proc_creation_win_mimikatz_command_line"),
    _rule(r"powershell(?:\.exe)?.{0,40}(?:-enc(?:odedcommand)?\b|frombase64string)", "PowerShell", "windows", "high",
          "Encoded/base64 PowerShell execution is the most common fileless scripting technique.",
          "Atomic Red Team T1059.001"),
    _rule(r"certutil.{0,30}(?:-urlcache|-split)", "Ingress Tool Transfer", "windows", "high",
          "certutil abused as a downloader is a documented LOLBAS payload-staging technique.",
          "LOLBAS: Certutil.exe"),
    _rule(r"certutil.{0,20}-decode", "Deobfuscate/Decode Files or Information", "windows", "high",
          "certutil -decode reverses base64 encoding on staged payloads.",
          "LOLBAS: Certutil.exe (Decode)"),
    _rule(r"mshta(?:\.exe)?.{0,60}https?://", "Mshta", "windows", "high",
          "mshta fetching/executing a remote .hta is the canonical LOLBAS proxy-execution payload.",
          "LOLBAS: Mshta.exe"),
    _rule(r"regsvr32.{0,40}(?:/i:https?://|scrobj\.dll)", "Regsvr32", "windows", "high",
          "The 'Squiblydoo' pattern - a classic AppLocker/AWL bypass.",
          "LOLBAS: Regsvr32.exe"),
    _rule(r"msbuild(?:\.exe)?.{0,60}\.(?:xml|csproj)", "MSBuild", "windows", "medium",
          "MSBuild compiling/executing inline tasks from a project file is a documented AWL-bypass technique.",
          "LOLBAS: Msbuild.exe"),
    _rule(r"installutil(?:\.exe)?.{0,40}/logfile=", "InstallUtil", "windows", "medium",
          "InstallUtil's uninstall-method execution is a documented AWL bypass.",
          "LOLBAS: InstallUtil.exe"),
    _rule(r"cmstp(?:\.exe)?.{0,40}\.inf\b", "CMSTP", "windows", "high",
          "CMSTP executing a malicious INF that registers a scriptlet is a documented UAC/AWL-bypass pattern.",
          "LOLBAS: Cmstp.exe"),
    _rule(r"reg(?:asm|svcs)(?:\.exe)?\b", "Regsvcs/Regasm", "windows", "medium",
          "Regasm/Regsvcs execute arbitrary code via an assembly's COM-registration export.",
          "LOLBAS: Regasm.exe, Regsvcs.exe"),
    _rule(r"odbcconf(?:\.exe)?.{0,20}regsvr", "Odbcconf", "windows", "medium",
          "odbcconf can load an arbitrary DLL via the REGSVR action, mirroring regsvr32 abuse.",
          "LOLBAS: Odbcconf.exe"),
    _rule(r"invoke-mimikatz|dumpcreds", "LSASS Memory", "windows", "high",
          "PowerSploit/Mimikatz PowerShell function names are unambiguous.",
          "Sigma: win_powershell_mimikatz"),
    _rule(r"set-mppreference.{0,40}-disablerealtimemonitoring\s+\$true", "Disable or Modify Tools", "windows", "high",
          "Disabling Defender real-time protection is a documented pre-payload defense-impairment step.",
          "Sigma: proc_creation_win_powershell_disable_defender"),
    _rule(r"wevtutil(?:\.exe)?\s+cl\b|event\s*id\s*[:=]?\s*1102\b|audit\s+log\s+was\s+cleared", "Clear Windows Event Logs", "windows", "high",
          "Clearing the Security log is textbook log-tampering.",
          "Sigma: proc_creation_win_wevtutil_clear_logs"),
    _rule(r"auditpol(?:\.exe)?.{0,30}(?:/clear|/success:disable)", "Disable or Modify Windows Event Log", "windows", "high",
          "Disabling audit categories via auditpol blinds Windows Security auditing.",
          "Sigma: proc_creation_win_auditpol_disable"),
    _rule(r"netsh(?:\.exe)?\s+advfirewall\s+set\s+allprofiles\s+state\s+off", "Windows Host Firewall", "windows", "high",
          "Disabling all firewall profiles is unambiguous defense impairment.",
          "Sigma: proc_creation_win_netsh_fw_disable"),
    _rule(r"vssadmin(?:\.exe)?\s+delete\s+shadows|wbadmin(?:\.exe)?\s+delete\s+catalog", "Inhibit System Recovery", "windows", "high",
          "Deleting shadow copies/backup catalog is the standard pre-ransomware step.",
          "Atomic Red Team T1490"),
    _rule(r"cipher(?:\.exe)?\s+/w\b", "File Deletion", "windows", "medium",
          "cipher /w overwrites deleted-file remnants to block forensic recovery.",
          "LOLBAS: Cipher.exe"),
    _rule(r"\b(?:rar|7z|winrar)(?:\.exe)?\b.{0,80}\s+a\b|\bcompress-archive\b", "Archive via Utility", "windows", "high",
          "Archive utilities are commonly used to stage collected files before exfiltration.",
          "Atomic Red Team T1560.001"),
    _rule(r"\bdestinationport\s*=\s*443\b|\bprotocol\s*=\s*tcp\b.{0,80}\bdestinationport\s*=\s*443\b", "Exfiltration Over Web Service", "windows", "medium",
          "Outbound HTTPS after collection/archive activity is consistent with web-service exfiltration staging.",
          "MITRE ATT&CK T1567"),
    _rule(r"reg(?:\.exe)?\s+add.{0,60}\\currentversion\\run\b", "Registry Run Keys / Startup Folder", "windows", "high",
          "Adding a Run/RunOnce value is the most common Windows persistence primitive.",
          "Atomic Red Team T1547.001"),
    _rule(r"schtasks.{0,30}/create.{0,30}/sc\b", "Scheduled Task", "windows", "high",
          "Direct CLI for registering a new Scheduled Task.",
          "Atomic Red Team T1053.005"),
    _rule(r"wmic(?:\.exe)?\s+process\s+call\s+create|wmiprvse", "Windows Management Instrumentation", "windows", "high",
          "Canonical WMI-based execution primitive.",
          "MITRE CAR CAR-2016-03-002"),
    _rule(r"psexecsvc|psexec(?:\.exe)?\b", "Service Execution", "windows", "high",
          "PsExec's temporary service is the archetypal lateral-movement execution tool.",
          "Atomic Red Team T1569.002"),

    _rule(r"event\s*id\s*[:=]?\s*4769.{0,250}0x17|0x17.{0,250}event\s*id\s*[:=]?\s*4769|"
          r"rc4.{0,20}service\s+ticket", "Kerberoasting", "windows", "high",
          "Requesting RC4 (not AES) service tickets for SPN accounts is the signature Kerberoasting pattern.",
          "Sigma: win_kerberoasting"),
    _rule(r"event\s*id\s*[:=]?\s*4768.{0,250}pre-auth.{0,10}0\b|"
          r"pre-auth.{0,10}0\b.{0,250}event\s*id\s*[:=]?\s*4768", "AS-REP Roasting", "windows", "high",
          "AS-REQ succeeding without a pre-auth timestamp flags accounts with no pre-auth required.",
          "Atomic Red Team T1558.004"),
    _rule(r"ntdsutil.{0,20}\bifm\b", "NTDS", "windows", "high",
          "ntdsutil 'Install From Media' is the standard NTDS.dit exfil method from a live DC.",
          "Atomic Red Team T1003.003"),
    _rule(r"(?:winword|excel|powerpnt)(?:\.exe)?.{0,80}(?:cmd\.exe|powershell|wscript)", "Malicious File", "windows", "high",
          "A child shell spawned from Office is the defining artifact of macro payload detonation.",
          "Sigma: proc_creation_win_office_shell"),
    _rule(r"iex\s*\(|net\.webclient|downloadstring", "PowerShell", "windows", "high",
          "The IEX download-cradle one-liner is the most common fileless PowerShell stager.",
          "Atomic Red Team T1059.001"),
    _rule(r'admin\$|\\\\[^\\\s]+\\admin\$|\bc\$\b', "SMB/Windows Admin Shares", "windows", "medium",
          "ADMIN$/C$ administrative share access is commonly used for remote file staging.",
          "existing pipeline heuristic"),
    _rule(r"sc(?:\.exe)?\s+create\b|event\s*id\s*[:=]?\s*7045\b", "Windows Service", "windows", "high",
          "New Windows service installation is a common persistence/lateral-movement primitive.",
          "existing pipeline heuristic"),
]

LINUX_RULES: list[MappingRule] = [
    _rule(r"a0=find\b.{0,80}-exec\b.{0,40}/(?:bin|usr/bin)/sh\s+-p", "Setuid and Setgid", "linux", "high",
          "find's -exec spawning a shell while find itself is SUID is a primary GTFOBins privesc primitive.",
          "GTFOBins: find"),
    _rule(r"key=perm_mod.{0,60}(?:chmod\s+(?:u\+s|4755))", "Setuid and Setgid", "linux", "high",
          "chmod u+s on a shell is directly planting a SUID backdoor.",
          "GTFOBins: chmod"),
    _rule(r"cap_setuid\+ep", "Setuid and Setgid", "linux", "medium",
          "Linux capabilities are an equivalent privesc path to classic SUID.",
          "GTFOBins: capabilities category"),
    _rule(r"python3?\s+-c\s+.{0,20}import\s+pty.{0,20}pty\.spawn", "Unix Shell", "linux", "high",
          "The pty.spawn one-liner is the standard TTY-upgrade for a raw reverse shell.",
          "GTFOBins: python"),
    _rule(r"\b(?:nc|ncat)\b.{0,40}-e\s+/bin/sh", "Unix Shell", "linux", "high",
          "-e directly execs a shell tied to the socket - a classic reverse/bind shell.",
          "GTFOBins: nc"),
    _rule(r"crontab\s+-e|/etc/cron\.d/|/var/spool/cron", "Cron", "linux", "high",
          "Direct cron modification is the canonical Linux persistence primitive.",
          "Atomic Red Team T1053.003"),
    _rule(r"\.ssh/authorized_keys", "SSH Authorized Keys", "linux", "high",
          "Writing authorized_keys plants persistent passwordless SSH access.",
          "Atomic Red Team T1098.004"),
    _rule(r"history\s+-c\b|unset\s+histfile|histsize=0", "Clear Command History", "linux", "high",
          "Clearing/disabling bash history is unambiguous shell-trail hiding.",
          "Atomic Red Team T1070.003"),
    _rule(r"ptrace.{0,20}(?:ptrace_attach|poketext)", "Ptrace System Calls", "linux", "medium",
          "ptrace-based code injection is Linux's primary process-injection primitive.",
          "Sigma: lnx_auditd_ptrace_process_injection"),
    _rule(r"ld_preload=|/etc/ld\.so\.preload", "Dynamic Linker Hijacking", "linux", "high",
          "Forcing a malicious .so to load before libc is the standard Linux userland-rootkit persistence mechanism.",
          "Atomic Red Team T1574.006"),
    _rule(r"base64\s+-d\s*\|\s*(?:bash|sh)\b", "Deobfuscate/Decode Files or Information", "linux", "high",
          "Base64-decoding a payload straight into a shell is a common Linux dropper pattern.",
          "Sigma: lnx_shell_base64_decode_exec"),
    _rule(r"(?:curl|wget)\s+.{0,80}\|\s*(?:bash|sh)\b", "Ingress Tool Transfer", "linux", "high",
          "Download-and-immediately-execute is the most common Linux staging one-liner.",
          "Atomic Red Team T1105"),
    _rule(r"/etc/systemd/system/[\w.-]+\.service", "Systemd Service", "linux", "high",
          "Dropping and enabling a new unit file is the standard modern Linux persistence-as-a-service technique.",
          "Atomic Red Team T1543.002"),
    _rule(r"useradd\b|usermod.{0,20}-ag\s+(?:sudo|wheel)", "Local Account", "linux", "high",
          "Creating or privileging a local user is a direct persistent-foothold action.",
          "Atomic Red Team T1136.001", parent_hint="Create Account"),
    _rule(r"\b(?:wtmp|btmp|lastlog)\b.{0,20}(?:>\s*/dev/null|truncate)", "Clear Linux or Mac System Logs", "linux", "high",
          "Zeroing wtmp/btmp/lastlog removes the login-session audit trail.",
          "MITRE CAR (log-tampering analytic)"),
    _rule(r"auditctl\s+-d\b|systemctl\s+stop\s+auditd|service\s+auditd\s+stop", "Disable or Modify Linux Audit System Log", "linux", "high",
          "Flushing rules or stopping auditd directly blinds this exact detection pipeline.",
          "Atomic Red Team T1562.012 (ID renamed in ATT&CK v19)"),
    _rule(r"iptables\s+-f\b|nft\s+flush\s+ruleset", "Disable or Modify System Firewall", "linux", "high",
          "Flushing all firewall rules removes host-based network restriction ahead of C2/lateral movement.",
          "Sigma: lnx_auditd_iptables_flush"),
    _rule(r"(?:cat|less|more)\s+/etc/shadow", "/etc/passwd and /etc/shadow", "linux", "high",
          "Direct /etc/shadow read is the simplest Linux hash-dump indicator.",
          "Atomic Red Team T1003.008"),
    _rule(r"\b(?:gdb|gcore)\b.{0,40}-p\s+\d+|gcore\s+\d+", "Proc Filesystem", "linux", "medium",
          "Dumping another process's memory via gdb/gcore is the Linux analogue of LSASS dumping.",
          "GTFOBins: gdb"),
    _rule(r"openssl\s+s_client\b", "Asymmetric Cryptography", "linux", "medium",
          "Ad-hoc TLS session via a stock binary is a documented technique for building an encrypted C2 channel.",
          "GTFOBins: openssl"),
    _rule(r"/dev/tcp/[\w.\-]+/\d+", "Cron", "linux", "high",
          "The /dev/tcp reverse-shell one-liner piped into crontab is a documented GTFOBins persistence trick.",
          "GTFOBins: crontab"),
    _rule(r"\(\)\s*\{\s*:;\s*\};?", "Web Shell", "linux", "high",
          "The literal Shellshock CVE-2014-6271 trigger expression in a request/log line is unambiguous - it has no benign use.",
          "Sigma: lnx_shellshock"),
    _rule(r"ln\s+-s\s+(?:-f\s+)?/etc/passwd", "Malicious Link", "linux", "high",
          "Symlinking to /etc/passwd is a documented technique (e.g. CVE-2021-3560/21Nails) for tricking a privileged process into overwriting it.",
          "Sigma: lnx_symlink_etc_passwd"),
    _rule(r"stack\s+smashing\s+detected|attempt\s+to\s+execute\s+code\s+on\s+stack\s+by",
          "Exploitation for Privilege Escalation", "linux", "high",
          "Kernel/glibc stack-protector messages logged to syslog are a direct signal of an attempted buffer-overflow exploit.",
          "Sigma: lnx_buffer_overflows"),
    _rule(r"useradd.{0,60}-u\s+0\b|usermod.{0,60}-u\s+0\b",
          "Account Manipulation", "linux", "high",
          "Creating/modifying an account to UID 0 grants it full root privileges - a distinct persistence primitive from ordinary account creation.",
          "Sigma: lnx_privileged_user_creation"),
]

AWS_RULES: list[MappingRule] = [
    _rule(r'"eventname"\s*:\s*"consolelogin".{0,200}"errormessage"\s*:\s*"failed authentication"',
          "Password Guessing", "aws", "medium",
          "Repeated failed logins against one account is the CloudTrail signature of password guessing.",
          "Sigma: aws_cloudtrail_console_login_failed_authentication"),
    _rule(r'(?=.*"eventname"\s*:\s*"consolelogin")(?=.*"mfaused"\s*:\s*"no")',
          "Cloud Accounts", "aws", "high",
          "Successful console login with no MFA challenge is a direct non-MFA-account-use indicator.",
          "Sigma: aws_cloudtrail_console_login_success_without_mfa", parent_hint="Valid Accounts"),
    _rule(r'"eventname"\s*:\s*"createaccesskey"', "Additional Cloud Credentials", "aws", "high",
          "Minting a key for another user establishes a persistent alternate credential.",
          "Sigma: aws_iam_backdoor_users_keys"),
    _rule(r'"eventname"\s*:\s*"(?:attachuserpolicy|putuserpolicy)".{0,200}administratoraccess',
          "Additional Cloud Roles", "aws", "high",
          "Attaching an admin-equivalent policy is direct privilege-escalation-via-account-manipulation.",
          "MITRE ATT&CK T1098.003"),
    _rule(r'"eventname"\s*:\s*"putbucket(?:policy|acl)".{0,300}(?:"aws":\s*"\*"|allusers)',
          "Data from Cloud Storage", "aws", "medium",
          "Making a bucket world-readable is a precondition for bulk data access.",
          "Sigma: aws_s3_data_management_tampering"),
    _rule(r'"eventname"\s*:\s*"(?:stoplogging|deletetrail|updatetrail)"',
          "Disable or Modify Cloud Log", "aws", "high",
          "Stopping/deleting/reconfiguring a CloudTrail trail is the clearest AWS log-tampering signal.",
          "Sigma: aws_cloudtrail_disable_logging"),
    _rule(r'"eventname"\s*:\s*"deleteflowlogs"', "Disable or Modify Cloud Log", "aws", "high",
          "Deleting VPC Flow Logs removes network telemetry.",
          "Sigma: aws_cloudtrail_vpc_flow_logs_deleted"),
    _rule(r'"eventname"\s*:\s*"deletedetector"|'
          r'"eventname"\s*:\s*"updatedetector".{0,300}"enable"\s*:\s*false',
          "Disable or Modify Cloud Log", "aws", "high",
          "Disabling/deleting the GuardDuty detector blinds AWS's managed threat detection.",
          "Sigma: aws_cloudtrail_guardduty_detector_deleted_or_updated"),
    _rule(r'"eventname"\s*:\s*"(?:stopconfigurationrecorder|deletedeliverychannel)"',
          "Disable or Modify Cloud Log", "aws", "high",
          "Stopping AWS Config removes configuration-change history.",
          "Sigma: aws_config_disable_recording"),
    _rule(r'"eventname"\s*:\s*"getsecretvalue"', "Cloud Secrets Management Stores", "aws", "high",
          "Secrets Manager retrieval is the direct signature of credential harvesting from a cloud secrets store.",
          "MITRE ATT&CK T1555.006"),
    _rule(r'"eventname"\s*:\s*"assumerole"', "Temporary Elevated Cloud Access", "aws", "medium",
          "AssumeRole is the primary way attackers pivot to higher-privileged roles via STS.",
          "Sigma: aws_sts_assumerole_misuse"),
    _rule(r'"eventname"\s*:\s*"getsessiontoken"', "Application Access Token", "aws", "medium",
          "Temporary credentials obtained via GetSessionToken can be exfiltrated and reused elsewhere.",
          "Sigma: aws_sts_getsessiontoken_misuse"),
    _rule(r'"eventname"\s*:\s*"getcalleridentity"', "Cloud Accounts", "aws", "medium",
          "Attackers commonly validate stolen/found keys with GetCallerIdentity before further action.",
          "Sigma: aws_sts_getcalleridentity_trufflehog", parent_hint="Valid Accounts"),
    _rule(r'"eventname"\s*:\s*"(?:listbuckets|getbucketacl)"', "Cloud Storage Object Discovery", "aws", "high",
          "Enumerating S3 objects/buckets after a foothold is a precise cloud discovery technique.",
          "Sigma: aws_enum_buckets"),
    _rule(r'"eventname"\s*:\s*"(?:listusers|listroles|getaccountauthorizationdetails)"',
          "Cloud Account", "aws", "high",
          "Bulk IAM principal enumeration is standard cloud reconnaissance.",
          "MITRE ATT&CK T1087.004", parent_hint="Account Discovery"),
    _rule(r"169\.254\.169\.254", "Cloud Instance Metadata API", "aws", "high",
          "Pulling role credentials from the instance metadata service is the standard cloud credential-theft path.",
          "Sigma: aws_cloudtrail_imds_malicious_usage"),
    _rule(r'"eventname"\s*:\s*"(?:sendcommand|startsession)"', "Cloud Services", "aws", "medium",
          "SSM RunCommand/Session Manager fleet-wide execution is a cloud-native lateral-movement channel.",
          "Sigma: aws_cloudtrail_ssm_malicious_usage"),
    _rule(r'"eventname"\s*:\s*"runinstances"', "Create Cloud Instance", "aws", "medium",
          "Spinning up a fresh instance can evade controls tied to existing monitored instances.",
          "MITRE ATT&CK T1578.002"),
    _rule(r'"eventname"\s*:\s*"importkeypair"', "SSH Authorized Keys", "aws", "medium",
          "Importing an attacker-controlled key pair establishes persistent SSH access to new EC2 instances.",
          "Sigma: aws_ec2_import_key_pair_activity"),
    _rule(r'"eventname"\s*:\s*"createfunctionurlconfig"', "Serverless Execution", "aws", "high",
          "Lambda function URLs are a documented serverless persistence/execution vector.",
          "Sigma: aws_lambda_function_url"),
    _rule(r'"eventname"\s*:\s*"(?:modifysnapshotattribute|createvolumepermission)"',
          "Transfer Data to Cloud Account", "aws", "high",
          "Sharing a snapshot/volume to an untrusted account is the CloudTrail signature of intra-cloud exfiltration.",
          "Sigma: aws_snapshot_backup_exfiltration"),
    _rule(r'"username"\s*:\s*"root".{0,200}"invokedby"|"type"\s*:\s*"root"',
          "Default Accounts", "aws", "medium",
          "Root-account API usage is commonly flagged as use of the account of last resort/highest privilege.",
          "Sigma: aws_root_account_usage"),
]

KUBERNETES_RULES: list[MappingRule] = [
    _rule(r'"verb"\s*:\s*"create".{0,200}"subresource"\s*:\s*"exec"', "Container Administration Command", "kubernetes", "high",
          "kubectl exec into a running pod is the direct container-admin-command primitive.",
          "Sigma: kubernetes_audit_exec_into_container"),
    _rule(r'"privileged"\s*:\s*true', "Escape to Host", "kubernetes", "high",
          "A privileged pod has full access to the host's devices/kernel capabilities.",
          "Sigma: kubernetes_audit_privileged_pod_creation"),
    _rule(r'"hostpath"\s*:', "Escape to Host", "kubernetes", "high",
          "Mounting the host filesystem into a pod is a direct container-breakout vector.",
          "Sigma: kubernetes_audit_hostpath_mount"),
    _rule(r'"hostnetwork"\s*:\s*true|"hostpid"\s*:\s*true', "Escape to Host", "kubernetes", "medium",
          "Sharing the host network/PID namespace weakens container isolation.",
          "MITRE ATT&CK for Containers matrix"),
    _rule(r"/var/run/(?:docker|crio)\.sock", "Escape to Host", "kubernetes", "high",
          "Mounting the container runtime socket gives a pod full host-level container control.",
          "MITRE ATT&CK for Containers matrix"),
    _rule(r'"resource"\s*:\s*"(?:rolebindings|clusterrolebindings)".{0,200}cluster-admin',
          "Additional Container Cluster Roles", "kubernetes", "high",
          "Binding an identity to cluster-admin is the direct RBAC privilege-escalation act.",
          "Sigma: kubernetes_audit_rolebinding_modification"),
    _rule(r'"verb"\s*:\s*"create".{0,100}"resource"\s*:\s*"serviceaccounts"', "Local Account", "kubernetes", "medium",
          "New ServiceAccount creation is a persistence primitive in the containers domain.",
          "Sigma: kubernetes_audit_serviceaccount_creation", parent_hint="Create Account"),
    _rule(r'"verb"\s*:\s*"(?:get|list)".{0,100}"resource"\s*:\s*"secrets"', "Container API", "kubernetes", "high",
          "Bulk Secret retrieval via the Kubernetes API is the direct container-native credential-harvesting technique.",
          "Sigma: kubernetes_audit_secrets_enumeration"),
    _rule(r'"verb"\s*:\s*"delete".{0,100}"resource"\s*:\s*"(?:secrets|configmaps)"', "Data Destruction", "kubernetes", "medium",
          "Deleting secrets/configmaps is destructive and can also serve as anti-forensics.",
          "Sigma: kubernetes_audit_secrets_modified_or_deleted"),
    _rule(r'"verb"\s*:\s*"delete".{0,100}"resource"\s*:\s*"events"', "Indicator Removal", "kubernetes", "high",
          "Deleting Kubernetes Event objects removes the cluster's own activity trail.",
          "Sigma: kubernetes_audit_events_deleted"),
    _rule(r'"resource"\s*:\s*"cronjobs"', "Container Orchestration Job", "kubernetes", "high",
          "CronJob creation/modification is the direct Kubernetes scheduled-execution persistence primitive.",
          "Sigma: kubernetes_audit_cronjob_modification"),
    _rule(r'"verb"\s*:\s*"create".{0,300}"namespace"\s*:\s*"kube-(?:system|public)"|'
          r'"namespace"\s*:\s*"kube-(?:system|public)".{0,300}"verb"\s*:\s*"create"',
          "Match Legitimate Resource Name or Location", "kubernetes", "medium",
          "Deploying in a system namespace blends malicious workloads in with trusted control-plane components.",
          "Sigma: kubernetes_audit_pod_in_system_namespace"),
    _rule(r'"resource"\s*:\s*"(?:mutatingwebhookconfigurations|validatingwebhookconfigurations)"',
          "Disable or Modify Tools", "kubernetes", "medium",
          "Tampering with admission-controller webhooks can neutralize policy-enforcement/security tooling.",
          "Sigma: kubernetes_audit_change_admission_controller"),
    _rule(r'"resource"\s*:\s*"(?:roles|clusterroles|rolebindings)".{0,150}"verb"\s*:\s*"list"|'
          r'"verb"\s*:\s*"list".{0,150}"resource"\s*:\s*"(?:roles|clusterroles|rolebindings)"',
          "Permission Groups Discovery", "kubernetes", "high",
          "Enumerating RBAC roles/bindings maps directly to permission-groups discovery.",
          "Sigma: kubernetes_audit_rbac_permisions_listing"),
    _rule(r'"decision"\s*:\s*"forbid"', "Valid Accounts", "kubernetes", "medium",
          "Repeated authorization denials from one identity suggests a compromised/misused account probing its access boundaries.",
          "Sigma: kubernetes_audit_unauthorized_unauthenticated_actions"),
    _rule(r'"verb"\s*:\s*"(?:delete)".{0,100}"resource"\s*:\s*"(?:deployments|daemonsets|statefulsets)"',
          "Data Destruction", "kubernetes", "medium",
          "Bulk workload deletion is a destructive impact action distinct from routine scaling/rollout operations.",
          "Sigma: kubernetes_audit_deployment_deleted"),
    # Additional coverage from MITRE ATT&CK's Containers matrix directly
    # (Sigma has no Kubernetes-specific rules upstream, unlike every other
    # platform here) - same audit-log-field style as the rules above, not
    # adapted from Falco: Falco's rule DSL targets syscalls/runtime events,
    # a different log shape than the verb/resource/objectRef audit JSON
    # this parser actually handles.
    _rule(r'"verb"\s*:\s*"(?:get|list)".{0,100}"resource"\s*:\s*"(?:services|endpoints)"',
          "Network Service Discovery", "kubernetes", "medium",
          "Enumerating cluster Services/Endpoints maps the internal network surface after a foothold.",
          "MITRE ATT&CK for Containers matrix"),
    _rule(r'system:serviceaccount:default:default', "Default Accounts", "kubernetes", "medium",
          "The default namespace's default ServiceAccount is the most commonly over-privileged, unremoved built-in identity in a cluster.",
          "MITRE ATT&CK for Containers matrix"),
    _rule(r'"verb"\s*:\s*"create".{0,150}"resource"\s*:\s*"services".{0,300}(?:loadbalancer|nodeport)',
          "External Remote Services", "kubernetes", "medium",
          "Exposing a Service via LoadBalancer/NodePort creates a new externally-reachable entry point into the cluster.",
          "MITRE ATT&CK for Containers matrix"),
    _rule(r'"resource"\s*:\s*"pods".{0,300}(?:xmrig|kinsing|kdevtmpfsi|kinsing_data|moneroocean)',
          "Malicious Image", "kubernetes", "high",
          "These image/binary names are well-documented Kubernetes cryptojacking campaigns (Kinsing/TeamTNT), not ambiguous generic signals.",
          "MITRE ATT&CK for Containers matrix"),
    _rule(r'"verb"\s*:\s*"create".{0,100}"resource"\s*:\s*"daemonsets"',
          "Container Service", "kubernetes", "medium",
          "A DaemonSet schedules a pod onto every node automatically, a distinct cluster-wide persistence primitive from a single Deployment/CronJob.",
          "MITRE ATT&CK for Containers matrix"),
    _rule(r'"verb"\s*:\s*"(?:get|list)".{0,100}"resource"\s*:\s*"configmaps"',
          "Credentials In Files", "kubernetes", "medium",
          "ConfigMaps are frequently (and insecurely) used to store credentials that belong in Secrets, unlike the Secrets API itself.",
          "MITRE ATT&CK for Containers matrix"),
    _rule(r'"verb"\s*:\s*"list".{0,150}"resource"\s*:\s*"(?:pods|namespaces|nodes|services)"',
          "Container and Resource Discovery", "kubernetes", "medium",
          "Bulk enumeration of pods/namespaces/nodes/services after a foothold is the direct container-and-resource discovery technique.",
          "MITRE ATT&CK for Containers matrix"),
]

MACOS_RULES: list[MappingRule] = [
    _rule(r"~?/library/launchagents/[\w.\-]+\.plist", "Launch Agent", "macos", "high",
          "Dropping a new LaunchAgent plist is the primary macOS user-level persistence primitive.",
          "Atomic Red Team T1543.001"),
    _rule(r"/library/launchdaemons/[\w.\-]+\.plist", "Launch Daemon", "macos", "high",
          "Dropping a new LaunchDaemon plist runs as root at boot - a common macOS persistence/privesc primitive.",
          "Atomic Red Team T1543.004"),
    _rule(r"launchctl\s+(?:load|bootstrap|kickstart)\b", "Launchctl", "macos", "high",
          "launchctl load/bootstrap is how a dropped LaunchAgent/Daemon plist actually gets activated.",
          "GTFOBins-style LOLBin: launchctl"),
    _rule(r"defaults\s+write.{0,60}\.plist\b|plutil\s+-(?:insert|replace)", "Plist File Modification", "macos", "medium",
          "Modifying a plist via defaults/plutil is how persistence or config-tampering payloads get installed without touching the file directly.",
          "MITRE ATT&CK T1647"),
    _rule(r"osascript\s+-e\b|osascript\s+.{0,40}\.scpt\b", "AppleScript", "macos", "high",
          "osascript executing inline or scripted AppleScript is the macOS analogue of a PowerShell one-liner.",
          "Atomic Red Team T1059.002"),
    _rule(r"security\s+(?:find-generic-password|find-internet-password|dump-keychain)", "Keychain", "macos", "high",
          "The `security` CLI dumping keychain items is the direct macOS credential-theft primitive.",
          "Atomic Red Team T1555.001"),
    _rule(r"spctl\s+--master-disable|xattr\s+-d\s+com\.apple\.quarantine", "Gatekeeper Bypass", "macos", "high",
          "Disabling Gatekeeper or stripping the quarantine attribute lets an unsigned/downloaded binary run without the usual macOS prompt.",
          "Sigma: macos_gatekeeper_bypass"),
    _rule(r"chflags\s+hidden\b|\bdot_clean\b|mv\s+\S+\s+\.\S", "Hidden Files and Directories", "macos", "medium",
          "Marking a file/directory hidden (chflags hidden, leading dot) is a lightweight anti-forensics step.",
          "Sigma: macos_hidden_file_creation"),
    _rule(r"osascript\s+.{0,80}(?:administrator\s+privileges|with\s+prompt)", "AppleScript", "macos", "medium",
          "AppleScript's `with administrator privileges`/prompt dialogs are a common macOS social-engineering privesc/phishing vector.",
          "Sigma: macos_osascript_privilege_prompt"),
    _rule(r"csrutil\s+disable|csrutil\s+enable\s+--without", "Disable or Modify Tools", "macos", "high",
          "Disabling System Integrity Protection removes macOS's core tamper-resistance for system files/processes.",
          "MITRE ATT&CK T1685 (Containers/macOS-applicable defense-impairment technique)"),
    _rule(r"tccutil\s+reset|/library/application support/com\.apple\.tcc/tcc\.db", "Disable or Modify Tools", "macos", "medium",
          "Resetting or directly editing the TCC privacy database bypasses macOS's permission-prompt security model.",
          "Sigma: macos_tcc_database_tampering"),
    _rule(r"curl\s+.{0,80}\|\s*(?:bash|sh|zsh)\b", "Ingress Tool Transfer", "macos", "high",
          "Download-and-immediately-execute via curl|sh is as common on macOS as on Linux.",
          "Atomic Red Team T1105"),
    _rule(r"history\s+-c\b|unset\s+histfile", "Clear Command History", "macos", "high",
          "Clearing/disabling shell history is unambiguous shell-trail hiding on macOS's default zsh too.",
          "Atomic Red Team T1070.003"),
]

WINDOWS_SIGMA_RULES: list[MappingRule] = [
_rule('(?:Cube0x0)', 'OS Credential Dumping', 'windows', 'high',
          'Hacktool Execution - PE Metadata (Sigma-sourced).',
          'Sigma: proc_creation_win_hktl_execution_via_pe_metadata.yml'),
    _rule('(?:\\ /dest:rdp\\-tcp\\#)', 'Remote Desktop Protocol', 'windows', 'high',
          'Suspicious RDP Redirect Using TSCON (Sigma-sourced).',
          'Sigma: proc_creation_win_tscon_rdp_redirect.yml'),
    _rule('(?:\\\\SpeechRuntime\\.exe)', 'Distributed Component Object Model', 'windows', 'high',
          'Suspicious Speech Runtime Binary Child Process (Sigma-sourced).',
          'Sigma: proc_creation_win_speechruntime_child_process.yml'),
    _rule('(?=.*(?:\\\\ssh\\.exe))(?=.*(?:\\ \\-R\\ )).+', 'SSH', 'windows', 'medium',
          'Port Forwarding Activity Via SSH.EXE (Sigma-sourced).',
          'Sigma: proc_creation_win_ssh_port_forward.yml'),
    _rule('(?=.*(?:\\-autoreconnect\\ ))(?=.*(?:\\-connect\\ ))(?=.*(?:\\-id:)).+', 'VNC', 'windows', 'high',
          'Suspicious UltraVNC Execution (Sigma-sourced).',
          'Sigma: proc_creation_win_ultravnc_susp_execution.yml'),
    _rule('(?=.*(?:\\\\ruby\\.exe))(?=.*(?:\\-i\\ ))(?=.*(?:\\-u\\ ))(?=.*(?:\\-p\\ )).+', 'Windows Remote Management', 'windows', 'medium',
          'HackTool - WinRM Access Via Evil-WinRM (Sigma-sourced).',
          'Sigma: proc_creation_win_hktl_evil_winrm.yml'),
    _rule('(?=.*(?:\\\\ping\\.exe))(?=.*(?:0x\\[a\\-fA\\-F0\\-9\\]\\{8\\})).+', 'Obfuscated Files or Information', 'windows', 'high',
          'Ping Hex IP (Sigma-sourced).',
          'Sigma: proc_creation_win_ping_hex_ip.yml'),
    _rule('(?:\\\\dnx\\.exe)', 'Compile After Delivery', 'windows', 'medium',
          'Potential Application Whitelisting Bypass via Dnx.EXE (Sigma-sourced).',
          'Sigma: proc_creation_win_dnx_execute_csharp_code.yml'),
    _rule('(?=.*(?:AUTHORI|AUTORI))(?=.*(?:\\\\taskmgr\\.exe)).+', 'Masquerading', 'windows', 'high',
          'Taskmgr as LOCAL_SYSTEM (Sigma-sourced).',
          'Sigma: proc_creation_win_taskmgr_localsystem.yml'),
    _rule('(?:\\\\u202e|\\[U\\+202E\\]|\u202e)', 'Right-to-Left Override', 'windows', 'high',
          'Potential Defense Evasion Via Right-to-Left Override (Sigma-sourced).',
          'Sigma: proc_creation_win_susp_right_to_left_override.yml'),
    _rule('(?:UserInitMprLogonScript)', 'Logon Script (Windows)', 'windows', 'high',
          'Potential Persistence Via Logon Scripts - CommandLine (Sigma-sourced).',
          'Sigma: proc_creation_win_registry_logon_script.yml'),
    _rule('(?:Offline_Winpwn|WinPwn\\ |WinPwn\\.exe|WinPwn\\.ps1)', 'Network Service Discovery', 'windows', 'high',
          'HackTool - WinPwn Execution (Sigma-sourced).',
          'Sigma: proc_creation_win_hktl_winpwn.yml'),
    _rule('(?=.*(?:\\\\at\\.exe))(?=.*(?:interactive)).+', 'At', 'windows', 'high',
          'Interactive AT Job (Sigma-sourced).',
          'Sigma: proc_creation_win_at_interactive_execution.yml'),
    _rule('(?=.*(?:rundll32\\.exe))(?=.*(?:Execute))(?=.*(?:RegRead))(?=.*(?:window\\.close)).+', 'Process Injection', 'windows', 'high',
          'Suspicious Rundll32 Invoking Inline VBScript (Sigma-sourced).',
          'Sigma: proc_creation_win_rundll32_inline_vbs.yml'),
    _rule('(?:\\\\HollowReaper\\.exe)', 'Process Hollowing', 'windows', 'high',
          'HackTool - HollowReaper Execution (Sigma-sourced).',
          'Sigma: proc_creation_win_hktl_hollowreaper.yml'),
    _rule('(?:rasdial\\.exe)', 'Command and Scripting Interpreter', 'windows', 'medium',
          'Suspicious RASdial Activity (Sigma-sourced).',
          'Sigma: proc_creation_win_rasdial_execution.yml'),
    _rule('(?=.*(?:\\\\rundll32\\.exe|\\\\cmd\\.exe))(?=.*(?:gthread\\-3\\.6\\.dll|\\\\Windows\\\\Temp\\\\tmp\\.bat|sigcmm\\-2\\.4\\.dll)).+', 'Windows Command Shell', 'windows', 'high',
          'HackTool - RedMimicry Winnti Playbook Execution (Sigma-sourced).',
          'Sigma: proc_creation_win_hktl_redmimicry_winnti_playbook.yml'),
    _rule('(?:\\\\bginfo\\.exe|\\\\bginfo64\\.exe)', 'Visual Basic', 'windows', 'medium',
          'Uncommon Child Process Of BgInfo.EXE (Sigma-sourced).',
          'Sigma: proc_creation_win_bginfo_uncommon_child_process.yml'),
    _rule('(?:st2stager)', 'Application Layer Protocol', 'windows', 'high',
          'HackTool - SILENTTRINITY Stager Execution (Sigma-sourced).',
          'Sigma: proc_creation_win_hktl_silenttrinity_stager.yml'),
    _rule('(?=.*(?:tunnel\\ ))(?=.*(?:service))(?=.*(?:internal\\-run))(?=.*(?:tunnel\\-service\\.log)).+', 'Web Protocols', 'windows', 'medium',
          'Visual Studio Code Tunnel Service Installation (Sigma-sourced).',
          'Sigma: proc_creation_win_vscode_tunnel_service_install.yml'),
    _rule('(?:\\\\HOSTNAME\\.EXE)', 'System Information Discovery', 'windows', 'low',
          'Suspicious Execution of Hostname (Sigma-sourced).',
          'Sigma: proc_creation_win_hostname_execution.yml'),
    _rule('(?=.*(?:nslookup))(?=.*(?:_ldap\\._tcp\\.dc\\._msdcs\\.)).+', 'Account Discovery', 'windows', 'high',
          'Network Reconnaissance Activity (Sigma-sourced).',
          'Sigma: proc_creation_win_nslookup_domain_discovery.yml'),
    _rule('(?=.*(?:\\ tunnel\\ ))(?=.*(?:cleanup\\ ))(?=.*(?:\\-config\\ |\\-connector\\-id\\ )).+', 'Proxy', 'windows', 'medium',
          'Cloudflared Tunnel Connections Cleanup (Sigma-sourced).',
          'Sigma: proc_creation_win_cloudflared_tunnel_cleanup.yml'),
    _rule('(?=.*(?:\\ tunnel\\ ))(?=.*(?:cleanup\\ ))(?=.*(?:\\-config\\ |\\-connector\\-id\\ )).+', 'Web Service', 'windows', 'medium',
          'Cloudflared Tunnel Connections Cleanup (Sigma-sourced).',
          'Sigma: proc_creation_win_cloudflared_tunnel_cleanup.yml'),
    _rule('(?=.*(?:\\\\rundll32\\.exe|\\\\cmd\\.exe))(?=.*(?:gthread\\-3\\.6\\.dll|\\\\Windows\\\\Temp\\\\tmp\\.bat|sigcmm\\-2\\.4\\.dll)).+', 'Native API', 'windows', 'high',
          'HackTool - RedMimicry Winnti Playbook Execution (Sigma-sourced).',
          'Sigma: proc_creation_win_hktl_redmimicry_winnti_playbook.yml'),
    _rule('(?=.*(?:\\-u\\ ))(?=.*(?:\\-p\\ ))(?=.*(?:\\^USER\\^|\\^PASS\\^)).+', 'Brute Force', 'windows', 'high',
          'HackTool - Hydra Password Bruteforce Execution (Sigma-sourced).',
          'Sigma: proc_creation_win_hktl_hydra.yml'),
    _rule('(?=.*(?:\\\\System\\\\CurrentControlSet\\\\Control\\\\Lsa))(?=.*(?:DisableRestrictedAdmin)).+', 'Modify Registry', 'windows', 'high',
          'RestrictedAdminMode Registry Value Tampering - ProcCreation (Sigma-sourced).',
          'Sigma: proc_creation_win_reg_lsa_disable_restricted_admin.yml'),
    _rule('(?=.*(?:\\\\Psr\\.exe))(?=.*(?:/start|\\-start)).+', 'Screen Capture', 'windows', 'medium',
          'Screen Capture Activity Via Psr.EXE (Sigma-sourced).',
          'Sigma: proc_creation_win_psr_capture_screenshots.yml'),
    _rule('(?:Get\\-Clipboard)', 'Clipboard Data', 'windows', 'medium',
          'PowerShell Get-Clipboard Cmdlet Via CLI (Sigma-sourced).',
          'Sigma: proc_creation_win_powershell_get_clipboard.yml'),
    _rule('(?=.*(?:\\\\SoundRecorder\\.exe))(?=.*(?:/FILE)).+', 'Audio Capture', 'windows', 'medium',
          'Audio Capture via SoundRecorder (Sigma-sourced).',
          'Sigma: proc_creation_win_soundrecorder_audio_capture.yml'),
    _rule('(?:\\\\mftrace\\.exe)', 'Trusted Developer Utilities Proxy Execution', 'windows', 'medium',
          'Potential Mftrace.EXE Abuse (Sigma-sourced).',
          'Sigma: proc_creation_win_mftrace_child_process.yml'),
    _rule('(?=.*(?:GZipStream))(?=.*(?:::Decompress)).+', 'Standard Encoding', 'windows', 'medium',
          'Gzip Archive Decode Via PowerShell (Sigma-sourced).',
          'Sigma: proc_creation_win_powershell_decode_gzip.yml'),
    _rule('(?=.*(?:e=Access\\&))(?=.*(?:y=Guest\\&))(?=.*(?:\\&p=))(?=.*(?:\\&c=))(?=.*(?:\\&k=)).+', 'External Remote Services', 'windows', 'medium',
          'Remote Access Tool - ScreenConnect Installation Execution (Sigma-sourced).',
          'Sigma: proc_creation_win_remote_access_tools_screenconnect_installation_cli_param.yml'),
    _rule('(?=.*(?:\\\\brave\\.exe|\\\\chrome\\.exe|\\\\msedge\\.exe|\\\\opera\\.exe|\\\\vivaldi\\.exe))(?=.*(?:\\-\\-load\\-extension=)).+', 'Browser Extensions', 'windows', 'medium',
          'Chromium Browser Instance Executed With Custom Extension (Sigma-sourced).',
          'Sigma: proc_creation_win_browsers_chromium_load_extension.yml'),
    _rule('(?=.*(?:\\-\\-remote\\-debugging\\-))(?=.*(?:\\-\\-user\\-data\\-dir))(?=.*(?:\\-\\-headless)).+', 'Browser Session Hijacking', 'windows', 'high',
          'Potential Data Stealing Via Chromium Headless Debugging (Sigma-sourced).',
          'Sigma: proc_creation_win_browsers_chromium_headless_debugging.yml'),
    _rule('(?=.*(?:UWhRCA))(?=.*(?:BAAAA)).+', 'Forced Authentication', 'windows', 'high',
          'Attempts of Kerberos Coercion Via DNS SPN Spoofing (Sigma-sourced).',
          'Sigma: proc_creation_win_kerberos_coercion_via_dns_spn_spoofing.yml'),
    _rule('(?=.*(?:\\\\ScreenConnect\\.Service\\.exe))(?=.*(?:\\\\cmd\\.exe|\\\\csc\\.exe)).+', 'Exploit Public-Facing Application', 'windows', 'high',
          'Remote Access Tool - ScreenConnect Server Web Shell Execution (Sigma-sourced).',
          'Sigma: proc_creation_win_remote_access_tools_screenconnect_webshell.yml'),
    _rule('(?=.*(?:\\[a\\-zA\\-Z\\]:\\\\\\\\))(?=.*(?:\\\\\\\\\\\\\\\\wsl\\.localhost)).+', 'Indirect Command Execution', 'windows', 'medium',
          'Windows Binary Executed From WSL (Sigma-sourced).',
          'Sigma: proc_creation_win_wsl_windows_binaries_execution.yml'),
    _rule('(?=.*(?:\\\\Hwp\\.exe))(?=.*(?:\\\\gbb\\.exe)).+', 'Exploitation for Client Execution', 'windows', 'high',
          'Suspicious HWP Sub Processes (Sigma-sourced).',
          'Sigma: proc_creation_win_hwp_exploits.yml'),
    _rule('(?=.*(?:\\\\java\\.exe|\\\\javaw\\.exe))(?=.*(?:SysAidServer)).+', 'Exploitation of Remote Services', 'windows', 'medium',
          'Suspicious SysAidServer Child (Sigma-sourced).',
          'Sigma: proc_creation_win_java_sysaidserver_susp_child_process.yml'),
    _rule('(?:LoadAssemblyFromPath\\ |LoadAssemblyFromNS\\ )', 'System Script Proxy Execution', 'windows', 'medium',
          'Assembly Loading Via CL_LoadAssembly.ps1 (Sigma-sourced).',
          'Sigma: proc_creation_win_powershell_cl_loadassembly.yml'),
    _rule('(?=.*(?:\\\\pubprn\\.vbs))(?=.*(?:script:)).+', 'PubPrn', 'windows', 'medium',
          'Pubprn.vbs Proxy Execution (Sigma-sourced).',
          'Sigma: proc_creation_win_lolbin_pubprn.yml'),
    _rule('(?=.*(?:\\\\devtoolslauncher\\.exe))(?=.*(?:LaunchForDeploy)).+', 'System Binary Proxy Execution', 'windows', 'high',
          'Devtoolslauncher.exe Executes Specified Binary (Sigma-sourced).',
          'Sigma: proc_creation_win_lolbin_devtoolslauncher.yml'),
    _rule('(?=.*(?:\\ msiexec))(?=.*(?:://)).+', 'Msiexec', 'windows', 'medium',
          'MsiExec Web Install (Sigma-sourced).',
          'Sigma: proc_creation_win_msiexec_web_install.yml'),
    _rule('(?=.*(?:\\\\TacticalAgent\\\\tacticalrmm\\.exe))(?=.*(?:\\-\\-api))(?=.*(?:\\-\\-auth))(?=.*(?:\\-\\-client\\-id))(?=.*(?:\\-\\-site\\-id))(?=.*(?:\\-\\-agent\\-type)).+', 'Remote Access Tools', 'windows', 'medium',
          'Remote Access Tool - TacticalRMM Agent Registration to Potentially Attacker-Controlled Server (Sigma-sourced).',
          'Sigma: proc_creation_win_remote_access_tools_tacticalrmm_agent_registration_via_cli.yml'),
    _rule('(?:\\\\QuickAssist\\.exe)', 'Remote Desktop Software', 'windows', 'low',
          'QuickAssist Execution (Sigma-sourced).',
          'Sigma: proc_creation_win_quickassist_execution.yml'),
    _rule('(?:\\\\msxsl\\.exe)', 'XSL Script Processing', 'windows', 'medium',
          'Msxsl.EXE Execution (Sigma-sourced).',
          'Sigma: proc_creation_win_msxsl_execution.yml'),
    _rule('(?=.*(?:\\\\takeown\\.exe))(?=.*(?:/f\\ ))(?=.*(?:/r)).+', 'Windows Permissions', 'windows', 'medium',
          'Suspicious Recursive Takeown (Sigma-sourced).',
          'Sigma: proc_creation_win_takeown_recursive_own.yml'),
    _rule('(?=.*(?:\\\\schtasks\\.exe))(?=.*(?:\\ /delete\\ ))(?=.*(?:/tn\\ \\\\\\*))(?=.*(?:\\ /f)).+', 'Service Stop', 'windows', 'high',
          'Delete All Scheduled Tasks (Sigma-sourced).',
          'Sigma: proc_creation_win_schtasks_delete_all.yml'),
    _rule('(?:Install\\-TransportAgent)', 'Transport Agent', 'windows', 'medium',
          'MSExchange Transport Agent Installation (Sigma-sourced).',
          'Sigma: proc_creation_win_powershell_msexchange_transport_agent.yml'),
    _rule('(?=.*(?:\\\\reg\\.exe))(?=.*(?:query))(?=.*(?:\\\\software\\\\))(?=.*(?:/v))(?=.*(?:svcversion)).+', 'Software Discovery', 'windows', 'medium',
          'Detected Windows Software Discovery (Sigma-sourced).',
          'Sigma: proc_creation_win_reg_software_discovery.yml'),
    _rule('(?=.*(?:\\\\shutdown\\.exe))(?=.*(?:/r\\ |/s\\ )).+', 'System Shutdown/Reboot', 'windows', 'medium',
          'Suspicious Execution of Shutdown (Sigma-sourced).',
          'Sigma: proc_creation_win_shutdown_execution.yml'),
    _rule('(?:C:\\\\Windows\\\\System32\\\\wpbbin\\.exe)', 'System Firmware', 'windows', 'high',
          'UEFI Persistence Via Wpbbin - ProcessCreation (Sigma-sourced).',
          'Sigma: proc_creation_win_wpbbin_potential_persistence.yml'),
    _rule('(?=.*(?:C:\\\\WINDOWS\\\\system32\\\\wbem\\\\scrcons\\.exe))(?=.*(?:C:\\\\Windows\\\\System32\\\\svchost\\.exe)).+', 'Windows Management Instrumentation Event Subscription', 'windows', 'medium',
          'WMI Persistence - Script Event Consumer (Sigma-sourced).',
          'Sigma: proc_creation_win_wmi_persistence_script_event_consumer.yml'),
    _rule('(?=.*(?:copy\\ ))(?=.*(?:/y\\ ))(?=.*(?:C:\\\\windows\\\\system32\\\\cmd\\.exe\\ C:\\\\windows\\\\system32\\\\sethc\\.exe)).+', 'Accessibility Features', 'windows', 'high',
          'Persistence Via Sticky Key Backdoor (Sigma-sourced).',
          'Sigma: proc_creation_win_cmd_sticky_keys_replace.yml'),
    _rule('(?=.*(?:\\-i|/install|\\-a|/add\\-driver|\\.inf))(?=.*(?:\\\\pnputil\\.exe)).+', 'Boot or Logon Autostart Execution', 'windows', 'medium',
          'Suspicious Driver Install by pnputil.exe (Sigma-sourced).',
          'Sigma: proc_creation_win_lolbin_susp_driver_installed_by_pnputil.yml'),
    _rule('(?=.*(?:\\\\regedit\\.exe))(?=.*(?:\\\\TrustedInstaller\\.exe|\\\\ProcessHacker\\.exe)).+', 'Abuse Elevation Control Mechanism', 'windows', 'high',
          'Regedit as Trusted Installer (Sigma-sourced).',
          'Sigma: proc_creation_win_regedit_trustedinstaller.yml'),
    _rule('(?:\\\\sdclt\\.exe)', 'Bypass User Account Control', 'windows', 'medium',
          'Sdclt Child Processes (Sigma-sourced).',
          'Sigma: proc_creation_win_sdclt_child_process.yml'),
    _rule('(?:ConsoleHost_history\\.txt|\\(Get\\-PSReadLineOption\\)\\.HistorySavePath)', 'Credentials In Files', 'windows', 'medium',
          'Potential PowerShell Console History Access Attempt via History File (Sigma-sourced).',
          'Sigma: proc_creation_win_powershell_console_history_file_access.yml'),
    _rule('(?:Export\\-PfxCertificate\\ |Export\\-Certificate\\ )', 'Private Keys', 'windows', 'medium',
          'Certificate Exported Via PowerShell (Sigma-sourced).',
          'Sigma: proc_creation_win_powershell_export_certificate.yml'),
    _rule('(?=.*(?:\\\\SYSVOL\\\\))(?=.*(?:\\\\policies\\\\)).+', 'Group Policy Preferences', 'windows', 'medium',
          'Suspicious SYSVOL Domain Group Policy Access (Sigma-sourced).',
          'Sigma: proc_creation_win_susp_sysvol_access.yml'),
    _rule('(?:X509Enrollment\\.CBinaryConverter|884e2002\\-217d\\-11da\\-b2a4\\-000e7bbb2b09)', 'Install Root Certificate', 'windows', 'medium',
          'Suspicious X509Enrollment - Process Creation (Sigma-sourced).',
          'Sigma: proc_creation_win_powershell_x509enrollment.yml'),
    _rule('(?:Offline_Winpwn|WinPwn\\ |WinPwn\\.exe|WinPwn\\.ps1)', 'Credentials from Password Stores', 'windows', 'high',
          'HackTool - WinPwn Execution (Sigma-sourced).',
          'Sigma: proc_creation_win_hktl_winpwn.yml'),
    _rule('(?:Offline_Winpwn|WinPwn\\ |WinPwn\\.exe|WinPwn\\.ps1)', 'Credentials from Web Browsers', 'windows', 'high',
          'HackTool - WinPwn Execution (Sigma-sourced).',
          'Sigma: proc_creation_win_hktl_winpwn.yml'),
    _rule('(?=.*(?:HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\Lsa))(?=.*(?:scecli\\\\0\\*))(?=.*(?:reg\\ add)).+', 'Password Filter DLL', 'windows', 'medium',
          'Dropping Of Password Filter DLL (Sigma-sourced).',
          'Sigma: proc_creation_win_reg_credential_access_via_password_filter.yml'),
    _rule('(?=.*(?:UWhRCA))(?=.*(?:BAAAA)).+', 'Name Resolution Poisoning and SMB Relay', 'windows', 'high',
          'Attempts of Kerberos Coercion Via DNS SPN Spoofing (Sigma-sourced).',
          'Sigma: proc_creation_win_kerberos_coercion_via_dns_spn_spoofing.yml'),
    _rule('(?:\\ /dest:rdp\\-tcp\\#)', 'RDP Hijacking', 'windows', 'high',
          'Suspicious RDP Redirect Using TSCON (Sigma-sourced).',
          'Sigma: proc_creation_win_tscon_rdp_redirect.yml'),
    _rule('(?=.*(?:\\\\reg\\.exe))(?=.*(?:\\\\SOFTWARE\\\\Microsoft\\\\Windows\\ NT\\\\CurrentVersion\\\\Winlogon\\\\SpecialAccounts\\\\UserList))(?=.*(?:add))(?=.*(?:/v))(?=.*(?:/d\\ 0)).+', 'Hidden Users', 'windows', 'medium',
          'Hiding User Account Via SpecialAccounts Registry Key - CommandLine (Sigma-sourced).',
          'Sigma: proc_creation_win_registry_special_accounts_hide_user.yml'),
    _rule('(?=.*(?:\\-\\-remote\\-debugging\\-))(?=.*(?:\\-\\-user\\-data\\-dir))(?=.*(?:\\-\\-headless)).+', 'Hidden Window', 'windows', 'high',
          'Potential Data Stealing Via Chromium Headless Debugging (Sigma-sourced).',
          'Sigma: proc_creation_win_browsers_chromium_headless_debugging.yml'),
    _rule('(?=.*(?:extrac32\\.exe))(?=.*(?:\\.cab))(?=.*(?::\\[\\^\\\\\\\\\\])).+', 'NTFS File Attributes', 'windows', 'medium',
          'Suspicious Extrac32 Alternate Data Stream Execution (Sigma-sourced).',
          'Sigma: proc_creation_win_lolbin_extrac32_ads.yml'),
    _rule('(?=.*(?:\\\\Winrar\\.exe|\\\\7zFM\\.exe|\\\\peazip\\.exe))(?=.*(?:\\\\isoburn\\.exe|\\\\PowerISO\\.exe|\\\\ImgBurn\\.exe)).+', 'Phishing', 'windows', 'high',
          'Phishing Pattern ISO in Archive (Sigma-sourced).',
          'Sigma: proc_creation_win_susp_archiver_iso_phishing.yml'),
    _rule('(?=.*(?:\\\\Hwp\\.exe))(?=.*(?:\\\\gbb\\.exe)).+', 'Spearphishing Attachment', 'windows', 'high',
          'Suspicious HWP Sub Processes (Sigma-sourced).',
          'Sigma: proc_creation_win_hwp_exploits.yml', parent_hint='Phishing'),
    _rule('(?:rundll32\\.exe|rundll32)', 'Lateral Tool Transfer', 'windows', 'high',
          'Rundll32 Execution Without Parameters (Sigma-sourced).',
          'Sigma: proc_creation_win_rundll32_without_parameters.yml'),
    _rule('(?=.*(?:\\\\ssh\\.exe))(?=.*(?::3389)).+', 'Protocol Tunneling', 'windows', 'high',
          'Potential RDP Tunneling Via SSH (Sigma-sourced).',
          'Sigma: proc_creation_win_ssh_rdp_tunneling.yml'),
    _rule('(?=.*(?:\\\\register\\-cimprovider\\.exe))(?=.*(?:\\-path))(?=.*(?:dll)).+', 'Hijack Execution Flow', 'windows', 'medium',
          'DLL Execution Via Register-cimprovider.exe (Sigma-sourced).',
          'Sigma: proc_creation_win_registry_cimprovider_dll_load.yml'),
    _rule('(?=.*(?:\\\\dnscmd\\.exe))(?=.*(?:/config))(?=.*(?:/serverlevelplugindll)).+', 'DLL', 'windows', 'high',
          'New DNS ServerLevelPluginDll Installed Via Dnscmd.EXE (Sigma-sourced).',
          'Sigma: proc_creation_win_dnscmd_install_new_server_level_plugin_dll.yml'),
    _rule('(?:Cube0x0)', 'Tool', 'windows', 'high',
          'Hacktool Execution - PE Metadata (Sigma-sourced).',
          'Sigma: proc_creation_win_hktl_execution_via_pe_metadata.yml'),
    _rule('(?=.*(?:\\\\gpresult\\.exe))(?=.*(?:/z|/v)).+', 'Group Policy Discovery', 'windows', 'medium',
          'Gpresult Display Group Policy Information (Sigma-sourced).',
          'Sigma: proc_creation_win_gpresult_execution.yml'),
]

LINUX_SIGMA_RULES: list[MappingRule] = [
_rule('(?=.*(?:/crontab))(?=.*(?:\\ \\-l)).+', 'System Service Discovery', 'linux', 'low',
          'Crontab Enumeration (Sigma-sourced).',
          'Sigma: proc_creation_lnx_crontab_enumeration.yml'),
    _rule('(?=.*(?:/base64))(?=.*(?:\\-d)).+', 'Obfuscated Files or Information', 'linux', 'low',
          'Decode Base64 Encoded Text (Sigma-sourced).',
          'Sigma: proc_creation_lnx_base64_decode.yml'),
    _rule('(?:/dev/shm/)', 'Fileless Storage', 'linux', 'high',
          'Process Execution From Shared Memory Directory (Sigma-sourced).',
          'Sigma: proc_creation_lnx_susp_exec_from_dev_shm.yml'),
    _rule('(?=.*(?:SYSCALL))(?=.*(?:split)).+', 'Data Transfer Size Limits', 'linux', 'low',
          'Split A File Into Pieces - Linux (Sigma-sourced).',
          'Sigma: lnx_auditd_split_file_into_pieces.yml'),
    _rule('(?:\\-\\(W\\|R\\)\\\\s\\?\\(\\\\s\\|"\\|\'\\)\\(\\[0\\-9a\\-fA\\-F\\]\\{2\\}\\\\s\\?\\)\\{2,20\\}\\(\\\\s\\|"\\|\'\\))', 'Network Service Discovery', 'linux', 'medium',
          'Pnscan Binary Data Transmission Activity (Sigma-sourced).',
          'Sigma: proc_creation_lnx_pnscan_binary_cli_pattern.yml'),
    _rule('(?:/at|/atd)', 'At', 'linux', 'low',
          'Scheduled Task/Job At (Sigma-sourced).',
          'Sigma: proc_creation_lnx_at_command.yml'),
    _rule('(?=.*(?:/dd))(?=.*(?:of=))(?=.*(?:/proc/))(?=.*(?:/mem)).+', 'Proc Memory', 'linux', 'medium',
          'Potential Linux Process Code Injection Via DD Utility (Sigma-sourced).',
          'Sigma: proc_creation_lnx_dd_process_injection.yml'),
    _rule('(?=.*(?:/capsh))(?=.*(?:\\ \\-\\-)).+', 'Command and Scripting Interpreter', 'linux', 'high',
          'Capsh Shell Invocation - Linux (Sigma-sourced).',
          'Sigma: proc_creation_lnx_capsh_shell_invocation.yml'),
    _rule('(?=.*(?:/esxcli))(?=.*(?:vm\\ process))(?=.*(?:kill)).+', 'Hypervisor CLI', 'linux', 'medium',
          'ESXi VM Kill Via ESXCLI (Sigma-sourced).',
          'Sigma: proc_creation_lnx_esxcli_vm_kill.yml'),
    _rule('(?=.*(?:/sudo))(?=.*(?:\\ \\-\\-chroot\\ |sudo\\ \\-R\\ )).+', 'Exploitation for Privilege Escalation', 'linux', 'low',
          'Linux Sudo Chroot Execution (Sigma-sourced).',
          'Sigma: proc_creation_lnx_chroot_execution.yml'),
    _rule('(?=.*(?:/curl))(?=.*(?:\\ \\-A\\ |\\ \\-\\-user\\-agent\\ )).+', 'Web Protocols', 'linux', 'medium',
          'Suspicious Curl Change User Agents - Linux (Sigma-sourced).',
          'Sigma: proc_creation_lnx_susp_curl_useragent.yml'),
    _rule('(?=.*(?:/grep))(?=.*(?:apached|frpc|sshd\\.sh|zone\\.arm)).+', 'System Information Discovery', 'linux', 'high',
          'Potential GobRAT File Discovery Via Grep (Sigma-sourced).',
          'Sigma: proc_creation_lnx_malware_gobrat_grep_payload_discovery.yml'),
    _rule('(?=.*(?:/apt|/apt\\-get))(?=.*(?:APT::Update::Pre\\-Invoke::=)).+', 'File and Directory Discovery', 'linux', 'medium',
          'Shell Invocation via Apt - Linux (Sigma-sourced).',
          'Sigma: proc_creation_lnx_apt_shell_execution.yml'),
    _rule('(?:http_proxy=|https_proxy=)', 'Proxy', 'linux', 'low',
          'Connection Proxy (Sigma-sourced).',
          'Sigma: proc_creation_lnx_proxy_connection.yml'),
    _rule('(?=.*(?:xclip))(?=.*(?:\\-sel))(?=.*(?:clip))(?=.*(?:\\-o)).+', 'Clipboard Data', 'linux', 'low',
          'Clipboard Collection with Xclip Tool (Sigma-sourced).',
          'Sigma: proc_creation_lnx_clipboard_collection.yml'),
    _rule('(?=.*(?:/esxcli))(?=.*(?:system\\ ))(?=.*(?:account\\ ))(?=.*(?:add\\ )).+', 'Create Account', 'linux', 'medium',
          'ESXi Account Creation Via ESXCLI (Sigma-sourced).',
          'Sigma: proc_creation_lnx_esxcli_user_account_creation.yml'),
    _rule('(?=.*(?:/amazon\\-ssm\\-agent))(?=.*(?:\\-register\\ ))(?=.*(?:\\-code\\ ))(?=.*(?:\\-id\\ ))(?=.*(?:\\-region\\ )).+', 'Remote Desktop Software', 'linux', 'medium',
          'Potential Linux Amazon SSM Agent Hijacking (Sigma-sourced).',
          'Sigma: proc_creation_lnx_ssm_agent_abuse.yml'),
    _rule('(?=.*(?:/chattr))(?=.*(?:\\ \\-i\\ )).+', 'Linux and Mac Permissions', 'linux', 'medium',
          'Remove Immutable File Attribute (Sigma-sourced).',
          'Sigma: proc_creation_lnx_chattr_immutable_removal.yml'),
    _rule('(?=.*(?:PATH))(?=.*(?:/sysrq|/sysctl\\.conf|/sysrq\\-trigger)).+', 'Service Stop', 'linux', 'medium',
          'Potential Abuse of Linux Magic System Request Key (Sigma-sourced).',
          'Sigma: lnx_auditd_magic_system_request_key.yml'),
    _rule('(?=.*(?:PATH))(?=.*(?:/sysrq|/sysctl\\.conf|/sysrq\\-trigger)).+', 'Endpoint Denial of Service', 'linux', 'medium',
          'Potential Abuse of Linux Magic System Request Key (Sigma-sourced).',
          'Sigma: lnx_auditd_magic_system_request_key.yml'),
    _rule('(?=.*(?:/grep|/egrep))(?=.*(?:nessusd|td\\-agent|packetbeat|filebeat|auditbeat|osqueryd|cbagentd|falcond)).+', 'Security Software Discovery', 'linux', 'low',
          'Security Software Discovery - Linux (Sigma-sourced).',
          'Sigma: proc_creation_lnx_security_software_discovery.yml'),
    _rule('(?=.*(?:/esxcli))(?=.*(?:vm\\ process))(?=.*(?:kill)).+', 'System Shutdown/Reboot', 'linux', 'medium',
          'ESXi VM Kill Via ESXCLI (Sigma-sourced).',
          'Sigma: proc_creation_lnx_esxcli_vm_kill.yml'),
    _rule('(?:/userdel)', 'Account Access Removal', 'linux', 'medium',
          'User Has Been Deleted Via Userdel (Sigma-sourced).',
          'Sigma: proc_creation_lnx_userdel.yml'),
    _rule('(?=.*(?:/setcap))(?=.*(?:cap_setuid)).+', 'Abuse Elevation Control Mechanism', 'linux', 'low',
          'Linux Setuid Capability Set on a Binary via Setcap Utility (Sigma-sourced).',
          'Sigma: proc_creation_lnx_cap_setuid.yml'),
    _rule('(?:\\ \\-name\\ \\.htpasswd|\\ \\-perm\\ \\-4000\\ )', 'Credentials In Files', 'linux', 'high',
          'Linux Recon Indicators (Sigma-sourced).',
          'Sigma: proc_creation_lnx_susp_recon_indicators.yml'),
    _rule('(?:/update\\-ca\\-certificates|/update\\-ca\\-trust)', 'Install Root Certificate', 'linux', 'low',
          'Install Root Certificate (Sigma-sourced).',
          'Sigma: proc_creation_lnx_install_root_certificate.yml'),
    _rule('(?=.*(?:/setcap))(?=.*(?:cap_setuid)).+', 'Compromise Host Software Binary', 'linux', 'low',
          'Linux Setuid Capability Set on a Binary via Setcap Utility (Sigma-sourced).',
          'Sigma: proc_creation_lnx_cap_setuid.yml'),
    _rule('(?=.*(?:/mount))(?=.*(?:hidepid=2))(?=.*(?:\\ \\-o\\ )).+', 'Hide Artifacts', 'linux', 'medium',
          'Mount Execution With Hidepid Parameter (Sigma-sourced).',
          'Sigma: proc_creation_lnx_mount_hidepid.yml'),
    _rule('(?:\\ \\-name\\ \\.htpasswd|\\ \\-perm\\ \\-4000\\ )', 'Client Configurations', 'linux', 'high',
          'Linux Recon Indicators (Sigma-sourced).',
          'Sigma: proc_creation_lnx_susp_recon_indicators.yml'),
]

AWS_SIGMA_RULES: list[MappingRule] = [
_rule('(?:TruffleHog)', 'OS Credential Dumping', 'aws', 'medium',
          'PUA - AWS TruffleHog Execution (Sigma-sourced).',
          'Sigma: aws_cloudtrail_pua_trufflehog.yml'),
    _rule('(?=.*(?:rds\\.amazonaws\\.com))(?=.*(?:ModifyDBCluster|DeleteDBCluster)).+', 'Automated Exfiltration', 'aws', 'high',
          'Modification or Deletion of an AWS RDS Cluster (Sigma-sourced).',
          'Sigma: aws_rds_dbcluster_actions.yml'),
    _rule('(?=.*(?:route53\\.amazonaws\\.com))(?=.*(?:TransferDomainToAnotherAwsAccount)).+', 'Account Manipulation', 'aws', 'low',
          'AWS Route 53 Domain Transferred to Another Account (Sigma-sourced).',
          'Sigma: aws_route_53_domain_transferred_to_another_account.yml'),
    _rule('(?=.*(?:ConsoleLogin))(?=.*(?:Failed\\ authentication)).+', 'Brute Force', 'aws', 'medium',
          'AWS ConsoleLogin Failed Authentication (Sigma-sourced).',
          'Sigma: aws_cloudtrail_console_login_failed_authentication.yml'),
    _rule('(?=.*(?:elasticache\\.amazonaws\\.com))(?=.*(?:CreateCacheSecurityGroup)).+', 'Create Account', 'aws', 'low',
          'AWS ElastiCache Security Group Created (Sigma-sourced).',
          'Sigma: aws_elasticache_security_group_created.yml'),
    _rule('(?=.*(?:elasticloadbalancing\\.amazonaws\\.com))(?=.*(?:ApplySecurityGroupsToLoadBalancer|SetSecurityGroups)).+', 'Exploit Public-Facing Application', 'aws', 'medium',
          'LoadBalancer Security Group Modification (Sigma-sourced).',
          'Sigma: aws_cloudtrail_security_group_change_loadbalancer.yml'),
    _rule('(?=.*(?:ec2\\.amazonaws\\.com))(?=.*(?:DisableEbsEncryptionByDefault)).+', 'Data Encrypted for Impact', 'aws', 'medium',
          'AWS EC2 Disable EBS Encryption (Sigma-sourced).',
          'Sigma: aws_ec2_disable_encryption.yml'),
    _rule('(?=.*(?:AssumedRole))(?=.*(?:Role)).+', 'Abuse Elevation Control Mechanism', 'aws', 'low',
          'AWS STS AssumeRole Misuse (Sigma-sourced).',
          'Sigma: aws_sts_assumerole_misuse.yml'),
    _rule('(?=.*(?:AssumedRole))(?=.*(?:Role)).+', 'Use Alternate Authentication Material', 'aws', 'low',
          'AWS STS AssumeRole Misuse (Sigma-sourced).',
          'Sigma: aws_sts_assumerole_misuse.yml'),
    _rule('(?:TruffleHog)', 'Credentials from Password Stores', 'aws', 'medium',
          'PUA - AWS TruffleHog Execution (Sigma-sourced).',
          'Sigma: aws_cloudtrail_pua_trufflehog.yml'),
    _rule('(?=.*(?:ec2\\.amazonaws\\.com))(?=.*(?:DisableEbsEncryptionByDefault)).+', 'Data Manipulation', 'aws', 'medium',
          'AWS EC2 Disable EBS Encryption (Sigma-sourced).',
          'Sigma: aws_ec2_disable_encryption.yml'),
    _rule('(?=.*(?:kms\\.amazonaws\\.com))(?=.*(?:ImportKeyMaterial|DeleteImportedKeyMaterial)).+', 'Install Digital Certificate', 'aws', 'high',
          'AWS KMS Imported Key Material Usage (Sigma-sourced).',
          'Sigma: aws_kms_import_key_material.yml'),
    _rule('(?=.*(?:ec2\\.amazonaws\\.com))(?=.*(?:CreateRoute)).+', 'Cloud Firewall', 'aws', 'medium',
          'New Network Route Added (Sigma-sourced).',
          'Sigma: aws_cloudtrail_new_route_added.yml'),
]

MACOS_SIGMA_RULES: list[MappingRule] = [
_rule('(?=.*(?:/usr/bin/base64))(?=.*(?:\\-d)).+', 'Obfuscated Files or Information', 'macos', 'low',
          'Decode Base64 Encoded Text -MacOs (Sigma-sourced).',
          'Sigma: proc_creation_macos_base64_decode.yml'),
    _rule('(?:/split)', 'Data Transfer Size Limits', 'macos', 'low',
          'Split A File Into Pieces (Sigma-sourced).',
          'Sigma: proc_creation_macos_split_file_into_pieces.yml'),
    _rule('(?:/tcpdump|/tshark)', 'Network Sniffing', 'macos', 'low',
          'Network Sniffing - MacOs (Sigma-sourced).',
          'Sigma: proc_creation_macos_network_sniffing.yml'),
    _rule(r'(?:/who\b|/w\b|/last\b|/lsof\b|/netstat\b)', 'System Network Connections Discovery', 'macos', 'low',
          'System Network Connections Discovery - MacOs (Sigma-sourced).',
          'Sigma: proc_creation_macos_system_network_connections_discovery.yml'),
    _rule('(?=.*(?:/openssl))(?=.*(?:/Volumes/))(?=.*(?:enc))(?=.*(?:\\-base64))(?=.*(?:\\ \\-d\\ )).+', 'Command and Scripting Interpreter', 'macos', 'medium',
          'Payload Decoded and Decrypted via Built-in Utilities (Sigma-sourced).',
          'Sigma: proc_creation_macos_payload_decoded_and_decrypted.yml'),
    _rule('(?=.*(?:osacompile))(?=.*(?:curl)).+', 'JavaScript', 'macos', 'medium',
          'Potential In-Memory Download And Compile Of Payloads (Sigma-sourced).',
          'Sigma: proc_creation_macos_susp_in_memory_download_and_compile.yml'),
    _rule('(?=.*(?:/touch))(?=.*(?:\\-t|\\-acmr|\\-d|\\-r)).+', 'Timestomp', 'macos', 'medium',
          'File Time Attribute Change (Sigma-sourced).',
          'Sigma: proc_creation_macos_change_file_time_attr.yml'),
    _rule('(?=.*(?:/dseditgroup))(?=.*(?:\\ \\-o\\ edit\\ ))(?=.*(?:\\ \\-a\\ ))(?=.*(?:\\ \\-t\\ user))(?=.*(?:admin)).+', 'Local Accounts', 'macos', 'medium',
          'User Added To Admin Group Via DseditGroup (Sigma-sourced).',
          'Sigma: proc_creation_macos_dseditgroup_add_to_admin_group.yml'),
    _rule('(?:/usr/sbin/screencapture)', 'Screen Capture', 'macos', 'low',
          'Screen Capture - macOS (Sigma-sourced).',
          'Sigma: proc_creation_macos_screencapture.yml'),
    _rule('(?=.*(?:/openssl))(?=.*(?:/Volumes/))(?=.*(?:enc))(?=.*(?:\\-base64))(?=.*(?:\\ \\-d\\ )).+', 'User Execution', 'macos', 'medium',
          'Payload Decoded and Decrypted via Built-in Utilities (Sigma-sourced).',
          'Sigma: proc_creation_macos_payload_decoded_and_decrypted.yml'),
    _rule('(?=.*(?:/chflags))(?=.*(?:hidden\\ )).+', 'System Binary Proxy Execution', 'macos', 'medium',
          'Hidden Flag Set On File/Directory Via Chflags - MacOS (Sigma-sourced).',
          'Sigma: proc_creation_macos_chflags_hidden_flag.yml'),
    _rule('(?:\\-\\-meshServiceName)', 'Remote Desktop Software', 'macos', 'medium',
          'Remote Access Tool - Potential MeshAgent Execution - MacOS (Sigma-sourced).',
          'Sigma: proc_creation_macos_remote_access_tools_meshagent_arguments.yml'),
    _rule('(?=.*(?:/csrutil))(?=.*(?:disable)).+', 'Security Software Discovery', 'macos', 'medium',
          'System Integrity Protection (SIP) Disabled (Sigma-sourced).',
          'Sigma: proc_creation_macos_csrutil_disable.yml'),
    _rule('(?:/shutdown|/reboot|/halt)', 'System Shutdown/Reboot', 'macos', 'low',
          'System Shutdown/Reboot - MacOs (Sigma-sourced).',
          'Sigma: proc_creation_macos_system_shutdown_reboot.yml'),
    _rule('(?=.*(?:/chflags))(?=.*(?:hidden\\ )).+', 'Credentials In Files', 'macos', 'medium',
          'Hidden Flag Set On File/Directory Via Chflags - MacOS (Sigma-sourced).',
          'Sigma: proc_creation_macos_chflags_hidden_flag.yml'),
    _rule('(?:\\.bash_history|\\.zsh_history|\\.zhistory|\\.history|\\.sh_history|fish_history)', 'Shell History', 'macos', 'medium',
          'Suspicious History File Operations (Sigma-sourced).',
          'Sigma: proc_creation_macos_susp_histfile_operations.yml'),
    _rule('(?=.*(?:/chflags))(?=.*(?:hidden\\ )).+', 'NTFS File Attributes', 'macos', 'medium',
          'Hidden Flag Set On File/Directory Via Chflags - MacOS (Sigma-sourced).',
          'Sigma: proc_creation_macos_chflags_hidden_flag.yml'),
    _rule('(?=.*(?:/hdiutil))(?=.*(?:attach\\ |mount\\ )).+', 'Spearphishing Attachment', 'macos', 'medium',
          'Disk Image Mounting Via Hdiutil - MacOS (Sigma-sourced).',
          'Sigma: proc_creation_macos_hdiutil_mount.yml', parent_hint='Phishing'),
]

WINDOWS_SIGMA_EXPANSION_RULES: list[MappingRule] = [
_rule('(?=.*(?:\\\\outlook\\.exe\\b))(?=.*(?:\\\\Microsoft\\\\Outlook\\\\VbaProject\\.OTM\\b)).+', 'Fallback Channels', 'windows', 'medium',
          'New Outlook Macro Created (Sigma-sourced).',
          'Sigma: file_event_win_office_outlook_macro_creation.yml'),
    _rule('(?:\\.portmap\\.io\\b)', 'Exfiltration Over C2 Channel', 'windows', 'medium',
          'Network Communication Initiated To Portmap.IO Domain (Sigma-sourced).',
          'Sigma: net_connection_win_domain_portmap.yml'),
    _rule('(?=.*(?:\\\\Windows\\\\System32\\\\Tasks))(?=.*(?:\\\\AppData\\\\|C:\\\\PerfLogs|\\\\Windows\\\\System32\\\\config\\\\systemprofile)).+', 'Scheduled Task/Job', 'windows', 'high',
          'Suspicious Scheduled Task Write to System32 Tasks (Sigma-sourced).',
          'Sigma: file_event_win_susp_task_write.yml'),
    _rule('(?=.*(?:update\\.onelaunch\\.com))(?=.*(?:\\\\OneLaunch\\.exe\\b)).+', 'Input Capture', 'windows', 'low',
          'DNS Query Request To OneLaunch Update Service (Sigma-sourced).',
          'Sigma: dns_query_win_onelaunch_update_service.yml'),
    _rule('(?=.*(?:\\\\ADExp\\.exe\\b|\\\\ADExplorer\\.exe\\b|\\\\ADExplorer64\\.exe\\b|\\\\ADExplorer64a\\.exe\\b))(?=.*(?:\\.dat\\b)).+', 'Domain Groups', 'windows', 'medium',
          'ADExplorer Writing Complete AD Snapshot Into .dat File (Sigma-sourced).',
          'Sigma: file_event_win_sysinternals_adexplorer_dump_written.yml'),
    _rule('(?:\\\\finger\\.exe\\b)', 'DNS', 'windows', 'high',
          'Network Connection Initiated via Finger.EXE (Sigma-sourced).',
          'Sigma: net_connection_win_finger.yml', parent_hint='Application Layer Protocol'),
    _rule('(?=.*(?:\\\\ADExp\\.exe\\b|\\\\ADExplorer\\.exe\\b|\\\\ADExplorer64\\.exe\\b|\\\\ADExplorer64a\\.exe\\b))(?=.*(?:\\.dat\\b)).+', 'Domain Account', 'windows', 'medium',
          'ADExplorer Writing Complete AD Snapshot Into .dat File (Sigma-sourced).',
          'Sigma: file_event_win_sysinternals_adexplorer_dump_written.yml', parent_hint='Account Discovery'),
    _rule('(?:\\.portmap\\.io\\b)', 'External Proxy', 'windows', 'medium',
          'Network Communication Initiated To Portmap.IO Domain (Sigma-sourced).',
          'Sigma: net_connection_win_domain_portmap.yml'),
    _rule('(?=.*(?:C:\\\\Windows\\\\PSEXEC\\-))(?=.*(?:\\.key\\b)).+', 'Domain Account', 'windows', 'high',
          'PSEXEC Remote Execution File Artefact (Sigma-sourced).',
          'Sigma: file_event_win_sysinternals_psexec_service_key.yml', parent_hint='Create Account'),
    _rule('(?=.*(?:\\\\outlook\\.exe\\b))(?=.*(?:\\\\Microsoft\\\\Outlook\\\\VbaProject\\.OTM\\b)).+', 'Office Application Startup', 'windows', 'medium',
          'New Outlook Macro Created (Sigma-sourced).',
          'Sigma: file_event_win_office_outlook_macro_creation.yml'),
    _rule('(?=.*(?:\\\\outlook\\.exe\\b))(?=.*(?:\\\\AppData\\\\Local\\\\Microsoft\\\\FORMS\\\\IPM|\\\\Local\\ Settings\\\\Application\\ Data\\\\Microsoft\\\\Forms)).+', 'Outlook Forms', 'windows', 'high',
          'Potential Persistence Via Outlook Form (Sigma-sourced).',
          'Sigma: file_event_win_office_outlook_newform.yml'),
    _rule('(?:\\\\AppData\\\\Local\\\\Microsoft\\\\Cache134\\.dat\\b|\\\\AppData\\\\Local\\\\Microsoft\\\\ExplorerSync\\.db\\b)', 'Supply Chain Compromise', 'windows', 'high',
          'Octopus Scanner Malware (Sigma-sourced).',
          'Sigma: file_event_win_mal_octopus_scanner.yml'),
    _rule('(?:\\\\AppData\\\\Local\\\\Microsoft\\\\Cache134\\.dat\\b|\\\\AppData\\\\Local\\\\Microsoft\\\\ExplorerSync\\.db\\b)', 'Compromise Software Dependencies and Development Tools', 'windows', 'high',
          'Octopus Scanner Malware (Sigma-sourced).',
          'Sigma: file_event_win_mal_octopus_scanner.yml'),
    _rule('(?=.*(?:\\\\mmc\\.exe\\b))(?=.*(?:\\\\vbscript\\.dll\\b|\\\\jscript\\.dll\\b|\\\\jscript9\\.dll\\b)).+', 'MMC', 'windows', 'medium',
          'MMC Loading Script Engines DLLs (Sigma-sourced).',
          'Sigma: image_load_win_mmc_loads_script_engine_dll.yml'),
    _rule('(?=.*(?:\\\\ADExp\\.exe\\b|\\\\ADExplorer\\.exe\\b|\\\\ADExplorer64\\.exe\\b|\\\\ADExplorer64a\\.exe\\b))(?=.*(?:\\.dat\\b)).+', 'Domain Trust Discovery', 'windows', 'medium',
          'ADExplorer Writing Complete AD Snapshot Into .dat File (Sigma-sourced).',
          'Sigma: file_event_win_sysinternals_adexplorer_dump_written.yml'),
    _rule('(?=.*(?:\\\\MSExchangeMailboxReplication\\.exe\\b))(?=.*(?:\\.aspx\\b|\\.asp\\b)).+', 'Web Shell', 'windows', 'high',
          'Suspicious MSExchangeMailboxReplication ASPX Write (Sigma-sourced).',
          'Sigma: file_event_win_susp_exchange_aspx_write.yml'),
    _rule('(?:Local\\\\Microsoft\\\\WindowsApps\\\\Get\\-Variable\\.exe\\b)', 'Event Triggered Execution', 'windows', 'high',
          'Suspicious Get-Variable.exe Creation (Sigma-sourced).',
          'Sigma: file_event_win_susp_get_variable.yml'),
    _rule('(?=.*(?:\\\\\\\\\\\\\\\\127\\.0\\.0))(?=.*(?:\\\\ADMIN\\$\\\\)).+', 'Screensaver', 'windows', 'medium',
          'Writing Local Admin Share (Sigma-sourced).',
          'Sigma: file_event_win_writing_local_admin_share.yml'),
    _rule('(?:\\\\Microsoft\\.VSCode_profile\\.ps1\\b)', 'PowerShell Profile', 'windows', 'medium',
          'VsCode Powershell Profile Modification (Sigma-sourced).',
          'Sigma: file_event_win_susp_vscode_powershell_profile.yml'),
    _rule('(?::\\\\Windows\\\\apppatch\\\\Custom\\\\|:\\\\Windows\\\\apppatch\\\\CustomSDB\\\\)', 'Shortcut Modification', 'windows', 'medium',
          'New Custom Shim Database Created (Sigma-sourced).',
          'Sigma: file_event_win_creation_new_shim_database.yml'),
    _rule('(?=.*(?:\\\\cmd\\.exe\\b|\\\\cscript\\.exe\\b|\\\\mshta\\.exe\\b|\\\\powershell\\.exe\\b|\\\\pwsh\\.exe\\b|\\\\wscript\\.exe\\b))(?=.*(?:\\\\AppData\\\\Local\\\\Packages\\\\Microsoft\\.WindowsTerminal_8wekyb3d8bbwe\\\\LocalState\\\\settings\\.json\\b)).+', 'Login Items', 'windows', 'medium',
          'Windows Terminal Profile Settings Modification By Uncommon Process (Sigma-sourced).',
          'Sigma: file_event_win_susp_windows_terminal_profile.yml'),
    _rule('(?:\\\\KeePass\\.exe\\b)', 'Password Managers', 'windows', 'high',
          'Remote Thread Created In KeePass.EXE (Sigma-sourced).',
          'Sigma: create_remote_thread_win_keepass.yml'),
    _rule('(?:\\.kirbi\\b|mimilsa\\.log\\b)', 'Steal or Forge Kerberos Tickets', 'windows', 'high',
          'HackTool - Mimikatz Kirbi File Creation (Sigma-sourced).',
          'Sigma: file_event_win_hktl_mimikatz_files.yml'),
    _rule('(?:\\\\regsvr32\\.exe\\b)', 'Component Object Model', 'windows', 'medium',
          'Network Connection Initiated By Regsvr32.EXE (Sigma-sourced).',
          'Sigma: net_connection_win_regsvr32_network_activity.yml'),
    _rule('(?:\\.devtunnels\\.ms\\b)', 'Exfiltration to Code Repository', 'windows', 'medium',
          'Network Connection Initiated To DevTunnels Domain (Sigma-sourced).',
          'Sigma: net_connection_win_domain_devtunnels.yml'),
    _rule('(?=.*(?::\\\\Users\\\\))(?=.*(?:\\\\\\.config\\\\rclone\\\\)).+', 'Exfiltration to Cloud Storage', 'windows', 'medium',
          'Rclone Config File Creation (Sigma-sourced).',
          'Sigma: file_event_win_rclone_config_files.yml'),
    _rule('(?::\\\\Windows\\ \\\\System32\\\\|:\\\\Windows\\ \\\\SysWOW64\\\\)', 'Path Interception by PATH Environment Variable', 'windows', 'high',
          'Trusted Path Bypass via Windows Directory Spoofing (Sigma-sourced).',
          'Sigma: image_load_win_trusted_path_bypass.yml'),
]

MACOS_SIGMA_EXPANSION_RULES: list[MappingRule] = [
_rule('(?=.*(?:/Library/StartupItems/|/System/Library/StartupItems))(?=.*(?:\\.plist\\b)).+', 'Startup Items', 'macos', 'low',
          'Startup Item File Created - MacOS (Sigma-sourced).',
          'Sigma: file_event_macos_susp_startup_item_created.yml'),
]

def _runtime_rule_key(rule: MappingRule) -> tuple[str, str, str | None]:
    return rule.source, rule.technique_name, rule.parent_hint


def _merge_compiled_runtime_rules(
    existing: list[MappingRule], platform: str
) -> list[MappingRule]:
    """Replace reviewed overlaps and append the remaining compiled rules.

    Replacing exact source/technique overlaps is essential: retaining the old
    raw-only entry beside its field-aware equivalent would reintroduce the raw
    false positives that the authoritative hybrid policy removes.
    """

    compiled = [
        _rule(
            **item["rule_kwargs"],
            structured_condition=item.get("structured_condition"),
            prefilter_terms=item.get("prefilter_terms"),
        )
        for item in load_runtime_rule_records(platform)
    ]
    compiled_keys = {_runtime_rule_key(rule) for rule in compiled}
    if len(compiled_keys) != len(compiled):
        raise RuntimeError(f"duplicate {platform} compiled runtime rule")
    return [rule for rule in existing if _runtime_rule_key(rule) not in compiled_keys] + compiled


WINDOWS_RUNTIME_RULES = _merge_compiled_runtime_rules(
    WINDOWS_RULES + WINDOWS_SIGMA_RULES + WINDOWS_SIGMA_EXPANSION_RULES,
    "windows",
)
LINUX_RUNTIME_RULES = _merge_compiled_runtime_rules(
    LINUX_RULES + LINUX_SIGMA_RULES,
    "linux",
)
MACOS_RUNTIME_RULES = _merge_compiled_runtime_rules(
    MACOS_RULES + MACOS_SIGMA_RULES + MACOS_SIGMA_EXPANSION_RULES,
    "macos",
)
AWS_RUNTIME_RULES = _merge_compiled_runtime_rules(
    AWS_RULES + AWS_SIGMA_RULES,
    "aws",
)
KUBERNETES_RUNTIME_RULES = _merge_compiled_runtime_rules(
    KUBERNETES_RULES,
    "kubernetes",
)


ALL_RULES: list[MappingRule] = [
    *WINDOWS_RUNTIME_RULES,
    *LINUX_RUNTIME_RULES,
    *AWS_RUNTIME_RULES,
    *KUBERNETES_RUNTIME_RULES,
    *MACOS_RUNTIME_RULES,
]

RULES_BY_PLATFORM: dict[str, list[MappingRule]] = {
    "windows": WINDOWS_RUNTIME_RULES,
    "linux": LINUX_RUNTIME_RULES,
    "aws": AWS_RUNTIME_RULES,
    "kubernetes": KUBERNETES_RUNTIME_RULES,
    "macos": MACOS_RUNTIME_RULES,
}
