"""AWS CloudTrail normalization adapter.

CloudTrail S3 objects are gzip-compressed JSON documents containing a
``Records`` array. The adapter also accepts a single record, a JSON array, or
NDJSON from a trusted streaming collector. Exact received bytes are stored
before decompression or parsing.

CloudTrail identifiers have different semantics and remain distinct:

* ``eventID`` identifies one CloudTrail event (and may repeat on duplicate
  delivery).
* ``sharedEventID`` links cross-account copies of one AWS action.
* ``requestID`` is generated by the called AWS service and is scoped to the
  recipient account, Region, and event source.

Log-file digest validation is performed by the trusted collection tier. Its
result is supplied through adapter configuration and can never be promoted by
an untrusted field in the event payload.
"""

from __future__ import annotations

import gzip
import hashlib
import io
import json
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Mapping
from urllib.parse import urlsplit

from correlation.models import (
    EntityKey,
    EventTimeQuality,
    NormalizedEvent,
    ParseStatus,
    Platform,
    RawEvidenceRef,
)
from correlation.ports import RawEvidenceStore


AWS_ADAPTER_VERSION = "1.0.0"
DEFAULT_MAX_PAYLOAD_BYTES = 16 * 1024 * 1024
DEFAULT_MAX_DECOMPRESSED_BYTES = 128 * 1024 * 1024
MAX_RESOURCE_REFERENCES = 1_000
MAX_AGGREGATE_BUCKETS = 5_000
MAX_INSIGHT_ATTRIBUTION_VALUES = 100
MAX_JSON_NESTING_DEPTH = 64
_EVENT_VERSION_RE = re.compile(r"^(?P<major>\d+)\.(?P<minor>\d+)$")
_ACCOUNT_ID_RE = re.compile(r"^\d{12}$")
_ARN_RE = re.compile(r"^arn:(?P<partition>aws(?:-[a-z0-9-]+)?):")
_PARTITION_RE = re.compile(r"^aws(?:-[a-z0-9-]+)?$")
_GUID_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    re.IGNORECASE,
)


class CloudTrailIntegrityStatus(str, Enum):
    """Trusted upstream integrity state for the received object."""

    UNVERIFIED = "unverified"
    AWS_DIGEST_VALIDATED = "aws_digest_validated"
    NOT_APPLICABLE_LIVE_SOURCE = "not_applicable_live_source"


@dataclass(frozen=True, slots=True)
class _InvalidJsonRecord:
    reason: str


def _text(value: Any) -> str | None:
    if value is None:
        return None
    rendered = str(value).strip()
    return rendered if rendered and rendered != "-" else None


def _mapping_get(value: Mapping[str, Any], name: str) -> Any:
    wanted = name.casefold()
    for key, child in value.items():
        if str(key).casefold() == wanted:
            return child
    return None


def _path(value: Mapping[str, Any], dotted: str) -> Any:
    current: Any = value
    for part in dotted.split("."):
        if not isinstance(current, Mapping):
            return None
        current = _mapping_get(current, part)
    return current


def _first(record: Mapping[str, Any], *paths: str) -> Any:
    for candidate in paths:
        value = _path(record, candidate)
        if value is not None and _text(value) is not None:
            return value
    return None


def _compact(value: Any) -> Any:
    if isinstance(value, Mapping):
        result = {
            str(key): _compact(child)
            for key, child in value.items()
            if child is not None
        }
        return {key: child for key, child in result.items() if child not in ({}, [])}
    if isinstance(value, (list, tuple)):
        result = [_compact(child) for child in value if child is not None]
        return [child for child in result if child not in ({}, [])]
    return value


def _timestamp(value: Any, *, utc_without_offset: bool = False) -> datetime | None:
    rendered = _text(value)
    if rendered is None:
        return None
    try:
        parsed = datetime.fromisoformat(rendered.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        if not utc_without_offset:
            return None
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def _json_items(payload: bytes) -> list[Mapping[str, Any] | _InvalidJsonRecord]:
    decoded = payload.decode("utf-8-sig")
    try:
        parsed = json.loads(
            decoded,
            object_pairs_hook=_strict_json_object,
            parse_constant=_reject_json_constant,
        )
    except (json.JSONDecodeError, ValueError):
        items: list[Mapping[str, Any] | _InvalidJsonRecord] = []
        for line in decoded.splitlines():
            if not line.strip():
                continue
            try:
                child = json.loads(
                    line,
                    object_pairs_hook=_strict_json_object,
                    parse_constant=_reject_json_constant,
                )
            except (json.JSONDecodeError, ValueError) as exc:
                items.append(_InvalidJsonRecord(str(exc)))
                continue
            items.append(
                child
                if isinstance(child, Mapping)
                else _InvalidJsonRecord("record is not a JSON object")
            )
        if not items:
            raise
        return items
    if isinstance(parsed, Mapping):
        records = _mapping_get(parsed, "Records")
        if isinstance(records, list):
            return [
                child
                if isinstance(child, Mapping)
                else _InvalidJsonRecord("record is not a JSON object")
                for child in records
            ]
        return [parsed]
    if isinstance(parsed, list):
        return [
            child
            if isinstance(child, Mapping)
            else _InvalidJsonRecord("record is not a JSON object")
            for child in parsed
        ]
    return [_InvalidJsonRecord("record is not a JSON object")]


def _reject_json_constant(value: str) -> None:
    raise ValueError(f"non-finite JSON number is not allowed: {value}")


def _strict_json_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    seen: set[str] = set()
    for key, value in pairs:
        normalized = str(key).casefold()
        if normalized in seen:
            raise ValueError(f"duplicate or case-ambiguous JSON key: {key}")
        seen.add(normalized)
        result[str(key)] = value
    return result


def _json_depth_is_safe(value: Any) -> bool:
    pending: list[tuple[Any, int]] = [(value, 1)]
    while pending:
        current, depth = pending.pop()
        if depth > MAX_JSON_NESTING_DEPTH:
            return False
        if isinstance(current, Mapping):
            pending.extend((child, depth + 1) for child in current.values())
        elif isinstance(current, list):
            pending.extend((child, depth + 1) for child in current)
    return True


def _version(value: Any) -> tuple[int, int] | None:
    rendered = _text(value)
    match = _EVENT_VERSION_RE.fullmatch(rendered or "")
    if match is None:
        return None
    return int(match.group("major")), int(match.group("minor"))


def _boolean(value: Any) -> bool | None:
    if isinstance(value, bool):
        return value
    rendered = (_text(value) or "").casefold()
    if rendered == "true":
        return True
    if rendered == "false":
        return False
    return None


def _safe_username(value: Any) -> str | None:
    rendered = _text(value)
    if rendered == "HIDDEN_DUE_TO_SECURITY_REASONS":
        return None
    return rendered


def _guid(value: Any) -> str | None:
    rendered = _text(value)
    return rendered.casefold() if rendered and _GUID_RE.fullmatch(rendered) else None


def _resource_views(value: Any) -> tuple[list[dict[str, Any]], bool]:
    if not isinstance(value, list):
        return [], False
    truncated = len(value) > MAX_RESOURCE_REFERENCES
    resources: list[dict[str, Any]] = []
    for child in value[:MAX_RESOURCE_REFERENCES]:
        if not isinstance(child, Mapping):
            continue
        view = _compact(
            {
                "arn": _text(_mapping_get(child, "ARN")),
                "account_id": _text(_mapping_get(child, "accountId")),
                "type": _text(_mapping_get(child, "type")),
            }
        )
        if view:
            resources.append(view)
    return resources, truncated


def _number(value: Any) -> int | float | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        return value
    return None


def _insight_attributions(value: Any) -> tuple[list[dict[str, Any]], bool]:
    if not isinstance(value, list):
        return [], False
    output: list[dict[str, Any]] = []
    value_count = 0
    truncated = False
    for attribution in value:
        if not isinstance(attribution, Mapping):
            continue
        result: dict[str, Any] = {
            "attribute": _text(_mapping_get(attribution, "attribute")),
        }
        for cohort in ("insight", "baseline"):
            entries = _mapping_get(attribution, cohort)
            if not isinstance(entries, list):
                continue
            rendered: list[dict[str, Any]] = []
            for entry in entries:
                if value_count >= MAX_INSIGHT_ATTRIBUTION_VALUES:
                    truncated = True
                    break
                if not isinstance(entry, Mapping):
                    continue
                rendered.append(
                    _compact(
                        {
                            "value": _text(_mapping_get(entry, "value")),
                            "average": _number(_mapping_get(entry, "average")),
                        }
                    )
                )
                value_count += 1
            result[cohort] = rendered
        # CloudTrail Lake's older flattened attribution representation.
        for field in (
            "insightValue",
            "insightAverage",
            "baselineValue",
            "baselineAverage",
        ):
            child = _mapping_get(attribution, field)
            if child is not None:
                result[field] = _number(child) if field.endswith("Average") else _text(child)
        compact = _compact(result)
        if compact:
            output.append(compact)
    return output, truncated


def _aggregated_dimensions(value: Any) -> tuple[list[dict[str, Any]], bool]:
    if not isinstance(value, Mapping):
        return [], False
    blocks: list[Mapping[str, Any]] = []
    primary = _mapping_get(value, "primaryDimension")
    if isinstance(primary, Mapping):
        blocks.append(primary)
    details = _mapping_get(value, "details")
    if isinstance(details, list):
        blocks.extend(child for child in details if isinstance(child, Mapping))

    output: list[dict[str, Any]] = []
    bucket_count = 0
    truncated = False
    for block in blocks:
        statistics = _mapping_get(block, "statistics")
        rendered: list[dict[str, Any]] = []
        if isinstance(statistics, list):
            for statistic in statistics:
                if bucket_count >= MAX_AGGREGATE_BUCKETS:
                    truncated = True
                    break
                if not isinstance(statistic, Mapping):
                    continue
                rendered.append(
                    _compact(
                        {
                            "name": _text(_mapping_get(statistic, "name")),
                            "value": _number(_mapping_get(statistic, "value")),
                        }
                    )
                )
                bucket_count += 1
        output.append(
            _compact(
                {
                    "dimension": _text(_mapping_get(block, "dimension")),
                    "aggregation_type": _text(
                        _mapping_get(block, "aggregationType")
                    ),
                    "statistics": rendered,
                }
            )
        )
    return output, truncated


@dataclass(frozen=True, slots=True)
class CloudTrailAdapter:
    evidence_store: RawEvidenceStore
    tenant_id: str
    source_instance_id: str
    aws_partition: str = "aws"
    integrity_status: CloudTrailIntegrityStatus = CloudTrailIntegrityStatus.UNVERIFIED
    integrity_proof_uri: str | None = None
    allowed_recipient_account_ids: tuple[str, ...] = ()
    allowed_regions: tuple[str, ...] = ()
    adapter_version: str = AWS_ADAPTER_VERSION
    max_payload_bytes: int = DEFAULT_MAX_PAYLOAD_BYTES
    max_decompressed_bytes: int = DEFAULT_MAX_DECOMPRESSED_BYTES

    def __post_init__(self) -> None:
        for name in ("tenant_id", "source_instance_id", "aws_partition", "adapter_version"):
            if not str(getattr(self, name) or "").strip():
                raise ValueError(f"{name} must not be empty")
        if not _PARTITION_RE.fullmatch(self.aws_partition):
            raise ValueError("aws_partition must be a valid AWS partition name")
        if not isinstance(self.integrity_status, CloudTrailIntegrityStatus):
            raise TypeError("integrity_status must be a CloudTrailIntegrityStatus")
        if self.integrity_status is CloudTrailIntegrityStatus.AWS_DIGEST_VALIDATED:
            proof_uri = _text(self.integrity_proof_uri)
            if not proof_uri:
                raise ValueError("digest-validated input requires integrity_proof_uri")
            parsed_proof = urlsplit(proof_uri)
            if parsed_proof.scheme not in {"file", "s3"}:
                raise ValueError("integrity_proof_uri must use file:// or s3://")
            if parsed_proof.scheme == "s3" and not parsed_proof.netloc:
                raise ValueError("s3 integrity_proof_uri must include a bucket")
            if parsed_proof.scheme == "file" and not parsed_proof.path:
                raise ValueError("file integrity_proof_uri must include a path")
            if (
                parsed_proof.username
                or parsed_proof.password
                or parsed_proof.query
                or parsed_proof.fragment
            ):
                raise ValueError("integrity_proof_uri must not contain credentials or query data")
        elif self.integrity_proof_uri is not None:
            raise ValueError("integrity_proof_uri is valid only for digest-validated input")
        if self.max_payload_bytes < 1 or self.max_decompressed_bytes < 1:
            raise ValueError("payload limits must be positive")
        normalized_accounts = tuple(str(value) for value in self.allowed_recipient_account_ids)
        normalized_regions = tuple(str(value).strip() for value in self.allowed_regions)
        object.__setattr__(self, "allowed_recipient_account_ids", normalized_accounts)
        object.__setattr__(self, "allowed_regions", normalized_regions)
        for account_id in normalized_accounts:
            if not _ACCOUNT_ID_RE.fullmatch(str(account_id)):
                raise ValueError("allowed recipient account IDs must be 12 digits")
        if any(not region for region in normalized_regions):
            raise ValueError("allowed regions must not contain empty values")

    def ingest(
        self,
        payload: bytes,
        *,
        media_type: str,
        collected_at: datetime,
        ingested_at: datetime | None = None,
        content_encoding: str | None = None,
    ) -> tuple[NormalizedEvent, ...]:
        raw = self.evidence_store.put(
            payload,
            tenant_id=self.tenant_id,
            platform=Platform.AWS,
            source_instance_id=self.source_instance_id,
            media_type=media_type,
            collected_at=collected_at,
            content_encoding=content_encoding,
        )
        accepted_at = ingested_at or collected_at
        if len(payload) > self.max_payload_bytes:
            return (
                self._unparseable(
                    raw,
                    accepted_at,
                    0,
                    f"payload exceeds configured {self.max_payload_bytes}-byte raw limit",
                ),
            )
        try:
            decoded = self._decode(payload, media_type, content_encoding)
            items = _json_items(decoded)
        except (
            gzip.BadGzipFile,
            EOFError,
            OSError,
            UnicodeDecodeError,
            json.JSONDecodeError,
            RecursionError,
            ValueError,
        ) as exc:
            return (self._unparseable(raw, accepted_at, 0, str(exc)),)

        events: list[NormalizedEvent] = []
        for ordinal, item in enumerate(items):
            if isinstance(item, _InvalidJsonRecord):
                events.append(
                    self._unparseable(raw, accepted_at, ordinal, item.reason)
                )
            elif not _json_depth_is_safe(item):
                events.append(
                    self._unparseable(
                        raw,
                        accepted_at,
                        ordinal,
                        f"record exceeds {MAX_JSON_NESTING_DEPTH}-level JSON depth limit",
                    )
                )
            elif not self._is_cloudtrail(item):
                events.append(
                    self._unparseable(raw, accepted_at, ordinal, "record is not a CloudTrail event")
                )
            else:
                events.append(self._normalize(raw, item, ordinal, accepted_at))
        return tuple(events) or (
            self._unparseable(raw, accepted_at, 0, "payload contains no event records"),
        )

    def _decode(
        self, payload: bytes, media_type: str, content_encoding: str | None
    ) -> bytes:
        encoding = (_text(content_encoding) or "").casefold()
        media = (_text(media_type) or "").casefold()
        compressed = payload.startswith(b"\x1f\x8b") or encoding in {"gzip", "x-gzip"} or media in {
            "application/gzip",
            "application/x-gzip",
        }
        if not compressed:
            return payload
        with gzip.GzipFile(fileobj=io.BytesIO(payload), mode="rb") as archive:
            decoded = archive.read(self.max_decompressed_bytes + 1)
        if len(decoded) > self.max_decompressed_bytes:
            raise ValueError(
                "gzip payload exceeds configured "
                f"{self.max_decompressed_bytes}-byte decompressed limit"
            )
        return decoded

    @staticmethod
    def _is_cloudtrail(record: Mapping[str, Any]) -> bool:
        event_type = _text(_mapping_get(record, "eventType"))
        if event_type == "AwsCloudTrailInsight":
            return _mapping_get(record, "eventVersion") is not None and (
                isinstance(_mapping_get(record, "insightDetails"), Mapping)
                or isinstance(_mapping_get(record, "insightContext"), Mapping)
            )
        if event_type == "AwsAggregatedEvent":
            return (
                _mapping_get(record, "eventVersion") is not None
                and isinstance(_mapping_get(record, "timeWindow"), Mapping)
                and isinstance(_mapping_get(record, "summary"), Mapping)
            )
        return all(
            _mapping_get(record, name) is not None
            for name in (
                "eventVersion",
                "userIdentity",
                "eventTime",
                "eventSource",
                "eventName",
            )
        ) and isinstance(_mapping_get(record, "userIdentity"), Mapping)

    def _event_id(self, identity: str) -> str:
        material = f"{self.tenant_id}\x00{self.source_instance_id}\x00{identity}"
        return "aws:" + hashlib.sha256(material.encode()).hexdigest()

    def _unparseable(
        self,
        raw: RawEvidenceRef,
        ingested_at: datetime,
        ordinal: int,
        warning: str,
    ) -> NormalizedEvent:
        return NormalizedEvent(
            event_id=self._event_id(f"raw:{raw.sha256}:{ordinal}"),
            tenant_id=self.tenant_id,
            platform=Platform.AWS,
            source_type="aws_cloudtrail",
            source_instance_id=self.source_instance_id,
            adapter_version=self.adapter_version,
            ingested_at=ingested_at,
            event_time_quality=EventTimeQuality.UNKNOWN,
            parse_status=ParseStatus.UNPARSEABLE,
            raw_evidence=raw,
            attributes={},
            parse_warnings=(warning,),
        )

    def _normalize(
        self,
        raw: RawEvidenceRef,
        record: Mapping[str, Any],
        ordinal: int,
        ingested_at: datetime,
    ) -> NormalizedEvent:
        parsed_version = _version(_mapping_get(record, "eventVersion"))
        if parsed_version is None:
            return self._unparseable(raw, ingested_at, ordinal, "invalid eventVersion")
        major, minor = parsed_version
        if major != 1:
            return self._unparseable(
                raw,
                ingested_at,
                ordinal,
                f"unsupported CloudTrail eventVersion major {major}",
            )

        event_type = _text(_mapping_get(record, "eventType"))
        if event_type == "AwsCloudTrailInsight":
            return self._normalize_insight(raw, record, ingested_at)
        if event_type == "AwsAggregatedEvent":
            return self._normalize_aggregated(raw, record, ingested_at)

        warnings: list[str] = []
        observed_at = _timestamp(_mapping_get(record, "eventTime"))
        if observed_at is None:
            observed_at = ingested_at
            quality = EventTimeQuality.COLLECTOR_ASSIGNED
            warnings.append("eventTime is missing or invalid")
        else:
            quality = EventTimeQuality.SOURCE_REPORTED

        raw_event_id = _text(_mapping_get(record, "eventID"))
        raw_shared_event_id = _text(_mapping_get(record, "sharedEventID"))
        event_id = _guid(raw_event_id)
        shared_event_id = _guid(raw_shared_event_id)
        request_id = _text(_mapping_get(record, "requestID"))
        event_source = _text(_mapping_get(record, "eventSource"))
        event_name = _text(_mapping_get(record, "eventName"))
        region = _text(_mapping_get(record, "awsRegion"))
        recipient_account = _text(_mapping_get(record, "recipientAccountId"))
        if raw_event_id is not None and event_id is None:
            warnings.append("eventID is not a valid CloudTrail GUID")
        elif event_id is None and minor >= 1:
            warnings.append("eventID is required by this eventVersion but is missing")
        if raw_shared_event_id is not None and shared_event_id is None:
            warnings.append("sharedEventID is not a valid CloudTrail GUID")
        if request_id is not None and len(request_id.encode("utf-8")) > 1_024:
            warnings.append("requestID exceeds the documented 1 KB maximum")
            request_id = None
        if region is None:
            warnings.append("awsRegion is missing")
        if recipient_account is not None and not _ACCOUNT_ID_RE.fullmatch(recipient_account):
            warnings.append("recipientAccountId is not a 12-digit AWS account ID")
        if (
            self.allowed_recipient_account_ids
            and recipient_account not in self.allowed_recipient_account_ids
        ):
            warnings.append("recipientAccountId is outside the configured source allowlist")
        if self.allowed_regions and region not in self.allowed_regions:
            warnings.append("awsRegion is outside the configured source allowlist")

        identity = _mapping_get(record, "userIdentity")
        identity = identity if isinstance(identity, Mapping) else {}
        identity_account = _text(_mapping_get(identity, "accountId"))
        principal_id = _text(_mapping_get(identity, "principalId"))
        principal_arn = _text(_mapping_get(identity, "arn"))
        access_key_id = _text(_mapping_get(identity, "accessKeyId"))
        session_context = _mapping_get(identity, "sessionContext")
        session_context = session_context if isinstance(session_context, Mapping) else {}
        session_issuer = _mapping_get(session_context, "sessionIssuer")
        session_issuer = session_issuer if isinstance(session_issuer, Mapping) else {}
        sign_in_session_arn = _text(_mapping_get(session_context, "signInSessionArn"))
        in_scope_of = _mapping_get(identity, "inScopeOf")
        in_scope_of = in_scope_of if isinstance(in_scope_of, Mapping) else {}
        on_behalf_of = _mapping_get(identity, "onBehalfOf")
        on_behalf_of = on_behalf_of if isinstance(on_behalf_of, Mapping) else {}
        invoked_by_delegate = _mapping_get(identity, "invokedByDelegate")
        invoked_by_delegate = (
            invoked_by_delegate if isinstance(invoked_by_delegate, Mapping) else {}
        )
        addendum = _mapping_get(record, "addendum")
        addendum = addendum if isinstance(addendum, Mapping) else {}
        raw_original_event_id = _text(_mapping_get(addendum, "originalEventID"))
        original_event_id = _guid(raw_original_event_id)
        original_request_id = _text(_mapping_get(addendum, "originalRequestID"))
        if raw_original_event_id is not None and original_event_id is None:
            warnings.append("addendum originalEventID is not a valid CloudTrail GUID")
        if original_request_id is not None and len(original_request_id.encode("utf-8")) > 1_024:
            warnings.append("addendum originalRequestID exceeds the documented 1 KB maximum")
            original_request_id = None
        resources, resources_truncated = _resource_views(_mapping_get(record, "resources"))
        if resources_truncated:
            warnings.append(
                f"resource references truncated to {MAX_RESOURCE_REFERENCES} entries"
            )

        account_scope = identity_account or recipient_account or "unknown-account"
        request_scope = ":".join(
            (
                self.aws_partition,
                recipient_account or "unknown-account",
                region or "unknown-region",
                event_source or "unknown-service",
            )
        )
        keys: list[EntityKey] = []
        if event_id:
            keys.append(EntityKey("cloudtrail_event_id", event_id, self.aws_partition))
        if shared_event_id:
            keys.append(
                EntityKey("cloudtrail_shared_event_id", shared_event_id, self.aws_partition)
            )
        if request_id:
            keys.append(EntityKey("cloud_request_id", request_id, request_scope))
        if original_event_id:
            keys.append(
                EntityKey("cloudtrail_original_event_id", original_event_id, self.aws_partition)
            )
        if original_request_id:
            keys.append(
                EntityKey("cloud_original_request_id", original_request_id, request_scope)
            )
        principal_scope = f"{self.aws_partition}:{account_scope}"
        if principal_id:
            keys.append(EntityKey("aws_principal_id", principal_id, principal_scope))
        if principal_arn:
            keys.append(EntityKey("aws_principal_arn", principal_arn, principal_scope))
        if access_key_id:
            keys.append(EntityKey("aws_access_key_id", access_key_id, principal_scope))
        if sign_in_session_arn:
            keys.append(
                EntityKey("aws_signin_session_arn", sign_in_session_arn, principal_scope)
            )
        identity_center_user_id = _text(_mapping_get(on_behalf_of, "userId"))
        identity_store_arn = _text(_mapping_get(on_behalf_of, "identityStoreArn"))
        if identity_center_user_id:
            keys.append(
                EntityKey(
                    "aws_identity_center_user_id",
                    identity_center_user_id,
                    identity_store_arn or principal_scope,
                )
            )
        delegated_provider_account = _text(
            _mapping_get(invoked_by_delegate, "accountId")
        )
        if delegated_provider_account:
            keys.append(
                EntityKey(
                    "aws_delegated_provider_account_id",
                    delegated_provider_account,
                    self.aws_partition,
                )
            )
        issuer_arn = _text(_mapping_get(session_issuer, "arn"))
        if issuer_arn:
            keys.append(EntityKey("aws_session_issuer_arn", issuer_arn, principal_scope))
        for resource in resources:
            arn = _text(resource.get("arn"))
            if arn and _ARN_RE.match(arn):
                keys.append(EntityKey("aws_resource_arn", arn, self.aws_partition))
        vpc_endpoint_id = _text(_mapping_get(record, "vpcEndpointId"))
        vpc_endpoint_account = _text(_mapping_get(record, "vpcEndpointAccountId"))
        if vpc_endpoint_id:
            endpoint_scope = ":".join(
                (
                    self.aws_partition,
                    vpc_endpoint_account or recipient_account or "unknown-account",
                    region or "unknown-region",
                )
            )
            keys.append(EntityKey("aws_vpc_endpoint_id", vpc_endpoint_id, endpoint_scope))

        error_code = _text(_mapping_get(record, "errorCode"))
        tls = _mapping_get(record, "tlsDetails")
        tls = tls if isinstance(tls, Mapping) else {}
        session_attributes = _mapping_get(session_context, "attributes")
        session_attributes = (
            session_attributes if isinstance(session_attributes, Mapping) else {}
        )
        attributes = _compact(
            {
                "event": {
                    "provider": "aws_cloudtrail",
                    "version": _text(_mapping_get(record, "eventVersion")),
                    "id": event_id,
                    "shared_id": shared_event_id,
                    "request_id": request_id,
                    "source": event_source,
                    "action": event_name,
                    "type": _text(_mapping_get(record, "eventType")),
                    "category": _text(_mapping_get(record, "eventCategory")),
                    "management": _boolean(_mapping_get(record, "managementEvent")),
                    "read_only": _boolean(_mapping_get(record, "readOnly")),
                    "outcome": "failure" if error_code else "success",
                    "error_code": error_code,
                },
                "cloud": {
                    "provider": "aws",
                    "partition": self.aws_partition,
                    "region": region,
                    "recipient_account_id": recipient_account,
                },
                "identity": {
                    "type": _text(_mapping_get(identity, "type")),
                    "principal_id": principal_id,
                    "arn": principal_arn,
                    "account_id": identity_account,
                    "access_key_id": access_key_id,
                    "user_name": _safe_username(_mapping_get(identity, "userName")),
                    "invoked_by": _text(_mapping_get(identity, "invokedBy")),
                    "invoked_by_delegate_account_id": delegated_provider_account,
                    "source_identity": _text(_mapping_get(session_context, "sourceIdentity")),
                    "sign_in_session_arn": sign_in_session_arn,
                    "session_issuer": {
                        "type": _text(_mapping_get(session_issuer, "type")),
                        "principal_id": _text(_mapping_get(session_issuer, "principalId")),
                        "arn": issuer_arn,
                        "account_id": _text(_mapping_get(session_issuer, "accountId")),
                        "user_name": _safe_username(_mapping_get(session_issuer, "userName")),
                    },
                    "session": {
                        "creation_date": _text(_mapping_get(session_attributes, "creationDate")),
                        "mfa_authenticated": _boolean(
                            _mapping_get(session_attributes, "mfaAuthenticated")
                        ),
                    },
                    "on_behalf_of": {
                        "user_id": _text(_mapping_get(on_behalf_of, "userId")),
                        "identity_store_arn": _text(
                            _mapping_get(on_behalf_of, "identityStoreArn")
                        ),
                    },
                    "in_scope_of": {
                        "source_arn": _text(_mapping_get(in_scope_of, "sourceArn")),
                        "issuer_type": _text(_mapping_get(in_scope_of, "issuerType")),
                        "credentials_issued_to": _text(
                            _mapping_get(in_scope_of, "credentialsIssuedTo")
                        ),
                    },
                },
                "network": {
                    "source_address": _text(_mapping_get(record, "sourceIPAddress")),
                    "user_agent": _text(_mapping_get(record, "userAgent")),
                    "vpc_endpoint_id": vpc_endpoint_id,
                    "vpc_endpoint_account_id": vpc_endpoint_account,
                    "tls": {
                        "version": _text(_mapping_get(tls, "tlsVersion")),
                        "cipher_suite": _text(_mapping_get(tls, "cipherSuite")),
                        "client_host_header": _text(
                            _mapping_get(tls, "clientProvidedHostHeader")
                        ),
                    },
                },
                "resources": resources,
                "addendum": {
                    "reason": _text(_mapping_get(addendum, "reason")),
                    "updated_fields": _text(_mapping_get(addendum, "updatedFields")),
                    "original_event_id": original_event_id,
                    "original_request_id": original_request_id,
                },
                "evidence": {
                    "integrity_status": self.integrity_status.value,
                    "integrity_proof_uri": self.integrity_proof_uri,
                },
            }
        )
        fingerprint = hashlib.sha256(
            json.dumps(record, sort_keys=True, separators=(",", ":")).encode()
        ).hexdigest()
        identity_material = (
            f"cloudtrail:{event_id or 'missing'}:{recipient_account or 'missing'}:"
            f"{fingerprint}:raw:{raw.sha256}"
        )
        return NormalizedEvent(
            event_id=self._event_id(identity_material),
            tenant_id=self.tenant_id,
            platform=Platform.AWS,
            source_type="aws_cloudtrail",
            source_instance_id=self.source_instance_id,
            adapter_version=self.adapter_version,
            observed_at=observed_at,
            ingested_at=ingested_at,
            event_time_quality=quality,
            parse_status=ParseStatus.PARTIAL if warnings else ParseStatus.PARSED,
            raw_evidence=raw,
            native_event_id=event_id,
            native_sequence=None,
            entity_keys=tuple(keys),
            attributes=attributes,
            parse_warnings=tuple(warnings),
        )

    def _normalize_insight(
        self,
        raw: RawEvidenceRef,
        record: Mapping[str, Any],
        ingested_at: datetime,
    ) -> NormalizedEvent:
        warnings: list[str] = []
        observed_at = _timestamp(_mapping_get(record, "eventTime"))
        if observed_at is None:
            observed_at = ingested_at
            quality = EventTimeQuality.COLLECTOR_ASSIGNED
            warnings.append("eventTime is missing or invalid")
        else:
            quality = EventTimeQuality.SOURCE_REPORTED

        raw_event_id = _text(_mapping_get(record, "eventID"))
        raw_shared_event_id = _text(_mapping_get(record, "sharedEventID"))
        event_id = _guid(raw_event_id)
        shared_event_id = _guid(raw_shared_event_id)
        region = _text(_mapping_get(record, "awsRegion"))
        recipient_account = _text(_mapping_get(record, "recipientAccountId"))
        details = _mapping_get(record, "insightDetails")
        trail_shape = isinstance(details, Mapping)
        details = details if isinstance(details, Mapping) else {}
        if trail_shape:
            state = _text(_mapping_get(details, "state"))
            event_source = _text(_mapping_get(details, "eventSource"))
            event_name = _text(_mapping_get(details, "eventName"))
            insight_type = _text(_mapping_get(details, "insightType"))
            error_code = _text(_mapping_get(details, "errorCode"))
            context = _mapping_get(details, "insightContext")
        else:
            state = _text(_mapping_get(record, "insightState"))
            event_source = _text(_mapping_get(record, "insightEventSource"))
            event_name = _text(_mapping_get(record, "insightEventName"))
            insight_type = _text(_mapping_get(record, "insightType"))
            error_code = _text(_mapping_get(record, "insightErrorCode"))
            context = _mapping_get(record, "insightContext")
        context = context if isinstance(context, Mapping) else {}
        statistics = _mapping_get(context, "statistics")
        statistics = statistics if isinstance(statistics, Mapping) else context
        attributions, attribution_truncated = _insight_attributions(
            _mapping_get(context, "attributions")
        )
        if attribution_truncated:
            warnings.append(
                "Insight attribution values truncated to "
                f"{MAX_INSIGHT_ATTRIBUTION_VALUES} entries"
            )
        if raw_event_id is None:
            warnings.append("eventID is missing")
        elif event_id is None:
            warnings.append("eventID is not a valid CloudTrail GUID")
        if raw_shared_event_id is None:
            warnings.append("sharedEventID is missing")
        elif shared_event_id is None:
            warnings.append("sharedEventID is not a valid CloudTrail GUID")
        for field_name, value in (
            ("awsRegion", region),
            ("Insight state", state),
            ("Insight event source", event_source),
            ("Insight event name", event_name),
            ("Insight type", insight_type),
        ):
            if value is None:
                warnings.append(f"{field_name} is missing")
        if (
            self.allowed_recipient_account_ids
            and recipient_account not in self.allowed_recipient_account_ids
        ):
            warnings.append("recipientAccountId is outside the configured source allowlist")
        if self.allowed_regions and region not in self.allowed_regions:
            warnings.append("awsRegion is outside the configured source allowlist")
        if recipient_account is not None and not _ACCOUNT_ID_RE.fullmatch(recipient_account):
            warnings.append("recipientAccountId is not a 12-digit AWS account ID")
        if _text(_mapping_get(record, "eventCategory")) != "Insight":
            warnings.append("Insight eventCategory is not 'Insight'")

        keys: list[EntityKey] = []
        if event_id:
            keys.append(EntityKey("cloudtrail_event_id", event_id, self.aws_partition))
        if shared_event_id:
            keys.append(
                EntityKey("cloudtrail_insight_id", shared_event_id, self.aws_partition)
            )
        principal_scope = (
            f"{self.aws_partition}:{recipient_account or 'unknown-account'}"
        )
        for attribution in attributions:
            if attribution.get("attribute") != "userIdentityArn":
                continue
            for cohort in ("insight", "baseline"):
                values = attribution.get(cohort)
                if not isinstance(values, list):
                    continue
                for item in values:
                    arn = _text(item.get("value")) if isinstance(item, Mapping) else None
                    if arn and _ARN_RE.match(arn):
                        keys.append(
                            EntityKey(
                                "aws_attributed_principal_arn", arn, principal_scope
                            )
                        )

        attributes = _compact(
            {
                "event": {
                    "provider": "aws_cloudtrail",
                    "version": _text(_mapping_get(record, "eventVersion")),
                    "id": event_id,
                    "shared_id": shared_event_id,
                    "type": "AwsCloudTrailInsight",
                    "category": "Insight",
                    "source": event_source,
                    "action": event_name,
                },
                "cloud": {
                    "provider": "aws",
                    "partition": self.aws_partition,
                    "region": region,
                    "recipient_account_id": recipient_account,
                },
                "insight": {
                    "shape": "trail" if trail_shape else "event_data_store",
                    "source": _text(_mapping_get(record, "insightSource")),
                    "state": state,
                    "type": insight_type,
                    "error_code": error_code,
                    "statistics": {
                        "baseline_average": _number(
                            _first(statistics, "baseline.average", "baselineAverage")
                        ),
                        "insight_average": _number(
                            _first(statistics, "insight.average", "insightAverage")
                        ),
                        "baseline_duration": _number(
                            _mapping_get(statistics, "baselineDuration")
                        ),
                        "insight_duration": _number(
                            _mapping_get(statistics, "insightDuration")
                        ),
                    },
                    "attributions": attributions,
                },
                "evidence": {
                    "integrity_status": self.integrity_status.value,
                    "integrity_proof_uri": self.integrity_proof_uri,
                },
            }
        )
        fingerprint = hashlib.sha256(
            json.dumps(record, sort_keys=True, separators=(",", ":")).encode()
        ).hexdigest()
        identity_material = (
            f"insight:{event_id or 'missing'}:{recipient_account or 'missing'}:"
            f"{fingerprint}:raw:{raw.sha256}"
        )
        return NormalizedEvent(
            event_id=self._event_id(identity_material),
            tenant_id=self.tenant_id,
            platform=Platform.AWS,
            source_type="aws_cloudtrail_insight",
            source_instance_id=self.source_instance_id,
            adapter_version=self.adapter_version,
            observed_at=observed_at,
            ingested_at=ingested_at,
            event_time_quality=quality,
            parse_status=ParseStatus.PARTIAL if warnings else ParseStatus.PARSED,
            raw_evidence=raw,
            native_event_id=event_id,
            entity_keys=tuple(keys),
            attributes=attributes,
            parse_warnings=tuple(warnings),
        )

    def _normalize_aggregated(
        self,
        raw: RawEvidenceRef,
        record: Mapping[str, Any],
        ingested_at: datetime,
    ) -> NormalizedEvent:
        warnings: list[str] = []
        raw_event_id = _text(_mapping_get(record, "eventId"))
        event_id = _guid(raw_event_id)
        account_id = _text(_mapping_get(record, "accountId"))
        region = _text(_mapping_get(record, "awsRegion"))
        event_source = _text(_mapping_get(record, "eventSource"))
        time_window = _mapping_get(record, "timeWindow")
        time_window = time_window if isinstance(time_window, Mapping) else {}
        window_start = _timestamp(
            _mapping_get(time_window, "windowStart"), utc_without_offset=True
        )
        window_end = _timestamp(
            _mapping_get(time_window, "windowEnd"), utc_without_offset=True
        )
        if window_start is None:
            observed_at = ingested_at
            quality = EventTimeQuality.COLLECTOR_ASSIGNED
            warnings.append("aggregation windowStart is missing or invalid")
        else:
            observed_at = window_start
            quality = EventTimeQuality.SOURCE_REPORTED
        if window_end is None:
            warnings.append("aggregation windowEnd is missing or invalid")
        elif window_start is not None and window_end <= window_start:
            warnings.append("aggregation windowEnd must be after windowStart")
        if event_id is None:
            warnings.append(
                "eventId is missing"
                if raw_event_id is None
                else "eventId is not a valid CloudTrail GUID"
            )
        if account_id is None:
            warnings.append("accountId is missing")
        if region is None:
            warnings.append("awsRegion is missing")
        if event_source is None:
            warnings.append("eventSource is missing")
        if (
            self.allowed_recipient_account_ids
            and account_id not in self.allowed_recipient_account_ids
        ):
            warnings.append("accountId is outside the configured source allowlist")
        if self.allowed_regions and region not in self.allowed_regions:
            warnings.append("awsRegion is outside the configured source allowlist")
        if account_id is not None and not _ACCOUNT_ID_RE.fullmatch(account_id):
            warnings.append("accountId is not a 12-digit AWS account ID")
        if _text(_mapping_get(record, "eventCategory")) != "Aggregated":
            warnings.append("aggregated eventCategory is not 'Aggregated'")

        summary = _mapping_get(record, "summary")
        dimensions, dimensions_truncated = _aggregated_dimensions(summary)
        if dimensions_truncated:
            warnings.append(
                f"aggregate statistic buckets truncated to {MAX_AGGREGATE_BUCKETS} entries"
            )
        keys: list[EntityKey] = []
        if event_id:
            keys.append(EntityKey("cloudtrail_event_id", event_id, self.aws_partition))
        for dimension in dimensions:
            if dimension.get("dimension") != "resourceARN":
                continue
            statistics = dimension.get("statistics")
            if not isinstance(statistics, list):
                continue
            for statistic in statistics:
                arn = _text(statistic.get("name")) if isinstance(statistic, Mapping) else None
                if arn and _ARN_RE.match(arn):
                    keys.append(EntityKey("aws_resource_arn", arn, self.aws_partition))

        addendum = _mapping_get(record, "addendum")
        addendum = addendum if isinstance(addendum, Mapping) else {}
        attributes = _compact(
            {
                "event": {
                    "provider": "aws_cloudtrail",
                    "version": _text(_mapping_get(record, "eventVersion")),
                    "id": event_id,
                    "type": "AwsAggregatedEvent",
                    "category": "Aggregated",
                    "source": event_source,
                    "action": "aggregate",
                },
                "cloud": {
                    "provider": "aws",
                    "partition": self.aws_partition,
                    "region": region,
                    "recipient_account_id": account_id,
                },
                "aggregation": {
                    "window_start": window_start.isoformat() if window_start else None,
                    "window_end": window_end.isoformat() if window_end else None,
                    "window_size": _text(_mapping_get(time_window, "windowSize")),
                    "dimensions": dimensions,
                },
                "addendum": {"reason": _text(_mapping_get(addendum, "reason"))},
                "evidence": {
                    "integrity_status": self.integrity_status.value,
                    "integrity_proof_uri": self.integrity_proof_uri,
                },
            }
        )
        fingerprint = hashlib.sha256(
            json.dumps(record, sort_keys=True, separators=(",", ":")).encode()
        ).hexdigest()
        identity_material = (
            f"aggregate:{event_id or 'missing'}:{account_id or 'missing'}:"
            f"{fingerprint}:raw:{raw.sha256}"
        )
        return NormalizedEvent(
            event_id=self._event_id(identity_material),
            tenant_id=self.tenant_id,
            platform=Platform.AWS,
            source_type="aws_cloudtrail_aggregated",
            source_instance_id=self.source_instance_id,
            adapter_version=self.adapter_version,
            observed_at=observed_at,
            ingested_at=ingested_at,
            event_time_quality=quality,
            parse_status=ParseStatus.PARTIAL if warnings else ParseStatus.PARSED,
            raw_evidence=raw,
            native_event_id=event_id,
            entity_keys=tuple(keys),
            attributes=attributes,
            parse_warnings=tuple(warnings),
        )
