"""Shared, vendor-defined Sysmon event semantics."""

SYSMON_ACTIONS = {
    "1": "process_start",
    "2": "file_creation_time_change",
    "3": "network_connection",
    "4": "sensor_state_change",
    "5": "process_end",
    "6": "driver_load",
    "7": "image_load",
    "8": "remote_thread_create",
    "9": "raw_disk_read",
    "10": "process_access",
    "11": "file_create",
    "12": "registry_object_change",
    "13": "registry_value_set",
    "14": "registry_object_rename",
    "15": "file_stream_hash",
    "17": "named_pipe_create",
    "18": "named_pipe_connect",
    "19": "wmi_filter",
    "20": "wmi_consumer",
    "21": "wmi_binding",
    "22": "dns_query",
    "23": "file_delete",
    "24": "clipboard_change",
    "25": "process_tampering",
    "26": "file_delete_detected",
    "27": "file_block_executable",
    "28": "file_block_shredding",
    "29": "file_executable_detected",
}
